defaultSemverRangePrefix: ""

enableStrictSsl: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

#npmRegistryServer: "https://artifactory.sherwin.com/artifactory/api/npm/sherwin-npm-virtual/"

npmScopes:
  fortawesome:
    npmAuthToken: 20128D8C-BDB5-4DCC-AE9E-01ECB91BD7E6
    npmRegistryServer: "https://npm.fontawesome.com/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

unsafeHttpWhitelist:
  - "*.sherwin.com"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
