FROM node:8

ENV NODE_ENV=production

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install \
       git bash python ca-certificates openssl make gcc g++  \
    && apt-get clean

COPY . /app

WORKDIR /app

RUN rm -rf dist \
    && mkdir -p dist \
    && chmod +x ci/scripts/entrypoint.build.sh

ENTRYPOINT ["/app/ci/scripts/entrypoint.build.sh"]
