// flow-typed signature: 8f3e71adf9d5b856acf1bfa7909aae60
// flow-typed version: <<STUB>>/@fortawesome/react-fontawesome_v0.1.16/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/react-fontawesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/react-fontawesome' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fortawesome/react-fontawesome/index.es' {
  declare module.exports: any
}

// Filename aliases
declare module '@fortawesome/react-fontawesome/index.es.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/index.es'>
}
declare module '@fortawesome/react-fontawesome/index' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome'>
}
declare module '@fortawesome/react-fontawesome/index.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome'>
}
