// flow-typed signature: 718a2c661d026bd52697d56e70058fe7
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-template-literals_v6.22.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-template-literals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-template-literals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-es2015-template-literals/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-es2015-template-literals/lib/index' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-template-literals/lib'>;
}
declare module 'babel-plugin-transform-es2015-template-literals/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-template-literals/lib'>;
}
