// flow-typed signature: 20e8e63b14531189b934de41f11b8232
// flow-typed version: <<STUB>>/color-space_v^1.16.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color-space'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'color-space' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'color-space/ciecam' {
  declare module.exports: any;
}

declare module 'color-space/cmy' {
  declare module.exports: any;
}

declare module 'color-space/cmyk' {
  declare module.exports: any;
}

declare module 'color-space/coloroid' {
  declare module.exports: any;
}

declare module 'color-space/cubehelix' {
  declare module.exports: any;
}

declare module 'color-space/hcg' {
  declare module.exports: any;
}

declare module 'color-space/hcy' {
  declare module.exports: any;
}

declare module 'color-space/hpluv' {
  declare module.exports: any;
}

declare module 'color-space/hsi' {
  declare module.exports: any;
}

declare module 'color-space/hsl' {
  declare module.exports: any;
}

declare module 'color-space/hsluv' {
  declare module.exports: any;
}

declare module 'color-space/hsp' {
  declare module.exports: any;
}

declare module 'color-space/hsv' {
  declare module.exports: any;
}

declare module 'color-space/hwb' {
  declare module.exports: any;
}

declare module 'color-space/jpeg' {
  declare module.exports: any;
}

declare module 'color-space/lab' {
  declare module.exports: any;
}

declare module 'color-space/labh' {
  declare module.exports: any;
}

declare module 'color-space/lchab' {
  declare module.exports: any;
}

declare module 'color-space/lchuv' {
  declare module.exports: any;
}

declare module 'color-space/lms' {
  declare module.exports: any;
}

declare module 'color-space/luv' {
  declare module.exports: any;
}

declare module 'color-space/munsell' {
  declare module.exports: any;
}

declare module 'color-space/osaucs' {
  declare module.exports: any;
}

declare module 'color-space/rgb' {
  declare module.exports: any;
}

declare module 'color-space/tsl' {
  declare module.exports: any;
}

declare module 'color-space/ucs' {
  declare module.exports: any;
}

declare module 'color-space/uvw' {
  declare module.exports: any;
}

declare module 'color-space/xvycc' {
  declare module.exports: any;
}

declare module 'color-space/xyy' {
  declare module.exports: any;
}

declare module 'color-space/xyz' {
  declare module.exports: any;
}

declare module 'color-space/ycbcr' {
  declare module.exports: any;
}

declare module 'color-space/yccbccrc' {
  declare module.exports: any;
}

declare module 'color-space/ycgco' {
  declare module.exports: any;
}

declare module 'color-space/ydbdr' {
  declare module.exports: any;
}

declare module 'color-space/yes' {
  declare module.exports: any;
}

declare module 'color-space/yiq' {
  declare module.exports: any;
}

declare module 'color-space/ypbpr' {
  declare module.exports: any;
}

declare module 'color-space/yuv' {
  declare module.exports: any;
}

// Filename aliases
declare module 'color-space/ciecam.js' {
  declare module.exports: $Exports<'color-space/ciecam'>;
}
declare module 'color-space/cmy.js' {
  declare module.exports: $Exports<'color-space/cmy'>;
}
declare module 'color-space/cmyk.js' {
  declare module.exports: $Exports<'color-space/cmyk'>;
}
declare module 'color-space/coloroid.js' {
  declare module.exports: $Exports<'color-space/coloroid'>;
}
declare module 'color-space/cubehelix.js' {
  declare module.exports: $Exports<'color-space/cubehelix'>;
}
declare module 'color-space/hcg.js' {
  declare module.exports: $Exports<'color-space/hcg'>;
}
declare module 'color-space/hcy.js' {
  declare module.exports: $Exports<'color-space/hcy'>;
}
declare module 'color-space/hpluv.js' {
  declare module.exports: $Exports<'color-space/hpluv'>;
}
declare module 'color-space/hsi.js' {
  declare module.exports: $Exports<'color-space/hsi'>;
}
declare module 'color-space/hsl.js' {
  declare module.exports: $Exports<'color-space/hsl'>;
}
declare module 'color-space/hsluv.js' {
  declare module.exports: $Exports<'color-space/hsluv'>;
}
declare module 'color-space/hsp.js' {
  declare module.exports: $Exports<'color-space/hsp'>;
}
declare module 'color-space/hsv.js' {
  declare module.exports: $Exports<'color-space/hsv'>;
}
declare module 'color-space/hwb.js' {
  declare module.exports: $Exports<'color-space/hwb'>;
}
declare module 'color-space/index' {
  declare module.exports: $Exports<'color-space'>;
}
declare module 'color-space/index.js' {
  declare module.exports: $Exports<'color-space'>;
}
declare module 'color-space/jpeg.js' {
  declare module.exports: $Exports<'color-space/jpeg'>;
}
declare module 'color-space/lab.js' {
  declare module.exports: $Exports<'color-space/lab'>;
}
declare module 'color-space/labh.js' {
  declare module.exports: $Exports<'color-space/labh'>;
}
declare module 'color-space/lchab.js' {
  declare module.exports: $Exports<'color-space/lchab'>;
}
declare module 'color-space/lchuv.js' {
  declare module.exports: $Exports<'color-space/lchuv'>;
}
declare module 'color-space/lms.js' {
  declare module.exports: $Exports<'color-space/lms'>;
}
declare module 'color-space/luv.js' {
  declare module.exports: $Exports<'color-space/luv'>;
}
declare module 'color-space/munsell.js' {
  declare module.exports: $Exports<'color-space/munsell'>;
}
declare module 'color-space/osaucs.js' {
  declare module.exports: $Exports<'color-space/osaucs'>;
}
declare module 'color-space/rgb.js' {
  declare module.exports: $Exports<'color-space/rgb'>;
}
declare module 'color-space/tsl.js' {
  declare module.exports: $Exports<'color-space/tsl'>;
}
declare module 'color-space/ucs.js' {
  declare module.exports: $Exports<'color-space/ucs'>;
}
declare module 'color-space/uvw.js' {
  declare module.exports: $Exports<'color-space/uvw'>;
}
declare module 'color-space/xvycc.js' {
  declare module.exports: $Exports<'color-space/xvycc'>;
}
declare module 'color-space/xyy.js' {
  declare module.exports: $Exports<'color-space/xyy'>;
}
declare module 'color-space/xyz.js' {
  declare module.exports: $Exports<'color-space/xyz'>;
}
declare module 'color-space/ycbcr.js' {
  declare module.exports: $Exports<'color-space/ycbcr'>;
}
declare module 'color-space/yccbccrc.js' {
  declare module.exports: $Exports<'color-space/yccbccrc'>;
}
declare module 'color-space/ycgco.js' {
  declare module.exports: $Exports<'color-space/ycgco'>;
}
declare module 'color-space/ydbdr.js' {
  declare module.exports: $Exports<'color-space/ydbdr'>;
}
declare module 'color-space/yes.js' {
  declare module.exports: $Exports<'color-space/yes'>;
}
declare module 'color-space/yiq.js' {
  declare module.exports: $Exports<'color-space/yiq'>;
}
declare module 'color-space/ypbpr.js' {
  declare module.exports: $Exports<'color-space/ypbpr'>;
}
declare module 'color-space/yuv.js' {
  declare module.exports: $Exports<'color-space/yuv'>;
}
