// flow-typed signature: 4ed3942d9bf2fecf8584871ad236ac3f
// flow-typed version: <<STUB>>/color-util_v2.2.3/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'color-util' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'color-util/dist/color-util.min' {
  declare module.exports: any
}

declare module 'color-util/src/Color' {
  declare module.exports: any
}

declare module 'color-util/src/ColorUtil' {
  declare module.exports: any
}

declare module 'color-util/src/ConversionUtil' {
  declare module.exports: any
}

declare module 'color-util/src/Gradient' {
  declare module.exports: any
}

declare module 'color-util/src/gradientData/GradientData' {
  declare module.exports: any
}

declare module 'color-util/src/gradientData/GradientDataArray2D' {
  declare module.exports: any
}

declare module 'color-util/src/gradientData/GradientDataFlat1D' {
  declare module.exports: any
}

declare module 'color-util/src/gradientData/GradientDataFlat2D' {
  declare module.exports: any
}

declare module 'color-util/src/gradientData/GradientDataObject2D' {
  declare module.exports: any
}

declare module 'color-util/src/gradientData/GradientDataUtil' {
  declare module.exports: any
}

declare module 'color-util/src/Repeat' {
  declare module.exports: any
}

declare module 'color-util/src/types/Any' {
  declare module.exports: any
}

declare module 'color-util/src/types/Csshsl' {
  declare module.exports: any
}

declare module 'color-util/src/types/Csshsla' {
  declare module.exports: any
}

declare module 'color-util/src/types/Cssrgb' {
  declare module.exports: any
}

declare module 'color-util/src/types/Cssrgba' {
  declare module.exports: any
}

declare module 'color-util/src/types/Hex' {
  declare module.exports: any
}

declare module 'color-util/src/types/Hsl' {
  declare module.exports: any
}

declare module 'color-util/src/types/Hsv' {
  declare module.exports: any
}

declare module 'color-util/src/types/Int' {
  declare module.exports: any
}

declare module 'color-util/src/types/Intabgr' {
  declare module.exports: any
}

declare module 'color-util/src/types/Intrgba' {
  declare module.exports: any
}

declare module 'color-util/src/types/Rgb' {
  declare module.exports: any
}

declare module 'color-util/src/types/shared' {
  declare module.exports: any
}

declare module 'color-util/src/types/types' {
  declare module.exports: any
}

declare module 'color-util/src/Utils' {
  declare module.exports: any
}

declare module 'color-util/test/Color.spec' {
  declare module.exports: any
}

declare module 'color-util/test/ColorUtil.spec' {
  declare module.exports: any
}

declare module 'color-util/test/ConversionUtil.spec' {
  declare module.exports: any
}

declare module 'color-util/test/Gradient.spec' {
  declare module.exports: any
}

declare module 'color-util/test/types/Any.spec' {
  declare module.exports: any
}

declare module 'color-util/test/types/Csshsl.spec' {
  declare module.exports: any
}

declare module 'color-util/test/types/Csshsla.spec' {
  declare module.exports: any
}

declare module 'color-util/test/types/Cssrgb.spec' {
  declare module.exports: any
}

declare module 'color-util/test/types/Cssrgba.spec' {
  declare module.exports: any
}

declare module 'color-util/test/types/Hex.spec' {
  declare module.exports: any
}

declare module 'color-util/test/types/Hsl.spec' {
  declare module.exports: any
}

declare module 'color-util/test/types/Hsv.spec' {
  declare module.exports: any
}

declare module 'color-util/test/types/Int.spec' {
  declare module.exports: any
}

declare module 'color-util/test/types/Intabgr.spec' {
  declare module.exports: any
}

declare module 'color-util/test/types/Intrgba.spec' {
  declare module.exports: any
}

declare module 'color-util/test/types/Rgb.spec' {
  declare module.exports: any
}

declare module 'color-util/test/Utils.spec' {
  declare module.exports: any
}

declare module 'color-util/test/validator/GradientData.spec' {
  declare module.exports: any
}

declare module 'color-util/test/validator/GradientDataUtil.spec' {
  declare module.exports: any
}

declare module 'color-util/webpack.config' {
  declare module.exports: any
}

// Filename aliases
declare module 'color-util/dist/color-util.min.js' {
  declare module.exports: $Exports<'color-util/dist/color-util.min'>
}
declare module 'color-util/src/Color.js' {
  declare module.exports: $Exports<'color-util/src/Color'>
}
declare module 'color-util/src/ColorUtil.js' {
  declare module.exports: $Exports<'color-util/src/ColorUtil'>
}
declare module 'color-util/src/ConversionUtil.js' {
  declare module.exports: $Exports<'color-util/src/ConversionUtil'>
}
declare module 'color-util/src/Gradient.js' {
  declare module.exports: $Exports<'color-util/src/Gradient'>
}
declare module 'color-util/src/gradientData/GradientData.js' {
  declare module.exports: $Exports<'color-util/src/gradientData/GradientData'>
}
declare module 'color-util/src/gradientData/GradientDataArray2D.js' {
  declare module.exports: $Exports<'color-util/src/gradientData/GradientDataArray2D'>
}
declare module 'color-util/src/gradientData/GradientDataFlat1D.js' {
  declare module.exports: $Exports<'color-util/src/gradientData/GradientDataFlat1D'>
}
declare module 'color-util/src/gradientData/GradientDataFlat2D.js' {
  declare module.exports: $Exports<'color-util/src/gradientData/GradientDataFlat2D'>
}
declare module 'color-util/src/gradientData/GradientDataObject2D.js' {
  declare module.exports: $Exports<'color-util/src/gradientData/GradientDataObject2D'>
}
declare module 'color-util/src/gradientData/GradientDataUtil.js' {
  declare module.exports: $Exports<'color-util/src/gradientData/GradientDataUtil'>
}
declare module 'color-util/src/Repeat.js' {
  declare module.exports: $Exports<'color-util/src/Repeat'>
}
declare module 'color-util/src/types/Any.js' {
  declare module.exports: $Exports<'color-util/src/types/Any'>
}
declare module 'color-util/src/types/Csshsl.js' {
  declare module.exports: $Exports<'color-util/src/types/Csshsl'>
}
declare module 'color-util/src/types/Csshsla.js' {
  declare module.exports: $Exports<'color-util/src/types/Csshsla'>
}
declare module 'color-util/src/types/Cssrgb.js' {
  declare module.exports: $Exports<'color-util/src/types/Cssrgb'>
}
declare module 'color-util/src/types/Cssrgba.js' {
  declare module.exports: $Exports<'color-util/src/types/Cssrgba'>
}
declare module 'color-util/src/types/Hex.js' {
  declare module.exports: $Exports<'color-util/src/types/Hex'>
}
declare module 'color-util/src/types/Hsl.js' {
  declare module.exports: $Exports<'color-util/src/types/Hsl'>
}
declare module 'color-util/src/types/Hsv.js' {
  declare module.exports: $Exports<'color-util/src/types/Hsv'>
}
declare module 'color-util/src/types/Int.js' {
  declare module.exports: $Exports<'color-util/src/types/Int'>
}
declare module 'color-util/src/types/Intabgr.js' {
  declare module.exports: $Exports<'color-util/src/types/Intabgr'>
}
declare module 'color-util/src/types/Intrgba.js' {
  declare module.exports: $Exports<'color-util/src/types/Intrgba'>
}
declare module 'color-util/src/types/Rgb.js' {
  declare module.exports: $Exports<'color-util/src/types/Rgb'>
}
declare module 'color-util/src/types/shared.js' {
  declare module.exports: $Exports<'color-util/src/types/shared'>
}
declare module 'color-util/src/types/types.js' {
  declare module.exports: $Exports<'color-util/src/types/types'>
}
declare module 'color-util/src/Utils.js' {
  declare module.exports: $Exports<'color-util/src/Utils'>
}
declare module 'color-util/test/Color.spec.js' {
  declare module.exports: $Exports<'color-util/test/Color.spec'>
}
declare module 'color-util/test/ColorUtil.spec.js' {
  declare module.exports: $Exports<'color-util/test/ColorUtil.spec'>
}
declare module 'color-util/test/ConversionUtil.spec.js' {
  declare module.exports: $Exports<'color-util/test/ConversionUtil.spec'>
}
declare module 'color-util/test/Gradient.spec.js' {
  declare module.exports: $Exports<'color-util/test/Gradient.spec'>
}
declare module 'color-util/test/types/Any.spec.js' {
  declare module.exports: $Exports<'color-util/test/types/Any.spec'>
}
declare module 'color-util/test/types/Csshsl.spec.js' {
  declare module.exports: $Exports<'color-util/test/types/Csshsl.spec'>
}
declare module 'color-util/test/types/Csshsla.spec.js' {
  declare module.exports: $Exports<'color-util/test/types/Csshsla.spec'>
}
declare module 'color-util/test/types/Cssrgb.spec.js' {
  declare module.exports: $Exports<'color-util/test/types/Cssrgb.spec'>
}
declare module 'color-util/test/types/Cssrgba.spec.js' {
  declare module.exports: $Exports<'color-util/test/types/Cssrgba.spec'>
}
declare module 'color-util/test/types/Hex.spec.js' {
  declare module.exports: $Exports<'color-util/test/types/Hex.spec'>
}
declare module 'color-util/test/types/Hsl.spec.js' {
  declare module.exports: $Exports<'color-util/test/types/Hsl.spec'>
}
declare module 'color-util/test/types/Hsv.spec.js' {
  declare module.exports: $Exports<'color-util/test/types/Hsv.spec'>
}
declare module 'color-util/test/types/Int.spec.js' {
  declare module.exports: $Exports<'color-util/test/types/Int.spec'>
}
declare module 'color-util/test/types/Intabgr.spec.js' {
  declare module.exports: $Exports<'color-util/test/types/Intabgr.spec'>
}
declare module 'color-util/test/types/Intrgba.spec.js' {
  declare module.exports: $Exports<'color-util/test/types/Intrgba.spec'>
}
declare module 'color-util/test/types/Rgb.spec.js' {
  declare module.exports: $Exports<'color-util/test/types/Rgb.spec'>
}
declare module 'color-util/test/Utils.spec.js' {
  declare module.exports: $Exports<'color-util/test/Utils.spec'>
}
declare module 'color-util/test/validator/GradientData.spec.js' {
  declare module.exports: $Exports<'color-util/test/validator/GradientData.spec'>
}
declare module 'color-util/test/validator/GradientDataUtil.spec.js' {
  declare module.exports: $Exports<'color-util/test/validator/GradientDataUtil.spec'>
}
declare module 'color-util/webpack.config.js' {
  declare module.exports: $Exports<'color-util/webpack.config'>
}
