// flow-typed signature: 9011962ee21df93b827f35d624e8d3d6
// flow-typed version: <<STUB>>/cypress_v10.6.0/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cypress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cypress' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cypress/angular/dist' {
  declare module.exports: any
}

declare module 'cypress/lib/cli' {
  declare module.exports: any
}

declare module 'cypress/lib/cypress' {
  declare module.exports: any
}

declare module 'cypress/lib/errors' {
  declare module.exports: any
}

declare module 'cypress/lib/exec/info' {
  declare module.exports: any
}

declare module 'cypress/lib/exec/open' {
  declare module.exports: any
}

declare module 'cypress/lib/exec/run' {
  declare module.exports: any
}

declare module 'cypress/lib/exec/shared' {
  declare module.exports: any
}

declare module 'cypress/lib/exec/spawn' {
  declare module.exports: any
}

declare module 'cypress/lib/exec/versions' {
  declare module.exports: any
}

declare module 'cypress/lib/exec/xvfb' {
  declare module.exports: any
}

declare module 'cypress/lib/fs' {
  declare module.exports: any
}

declare module 'cypress/lib/logger' {
  declare module.exports: any
}

declare module 'cypress/lib/tasks/cache' {
  declare module.exports: any
}

declare module 'cypress/lib/tasks/download' {
  declare module.exports: any
}

declare module 'cypress/lib/tasks/get-folder-size' {
  declare module.exports: any
}

declare module 'cypress/lib/tasks/install' {
  declare module.exports: any
}

declare module 'cypress/lib/tasks/state' {
  declare module.exports: any
}

declare module 'cypress/lib/tasks/unzip' {
  declare module.exports: any
}

declare module 'cypress/lib/tasks/verify' {
  declare module.exports: any
}

declare module 'cypress/lib/util' {
  declare module.exports: any
}

declare module 'cypress/lib/VerboseRenderer' {
  declare module.exports: any
}

declare module 'cypress/mount-utils/dist' {
  declare module.exports: any
}

declare module 'cypress/react/dist/cypress-react.cjs' {
  declare module.exports: any
}

declare module 'cypress/react/dist/cypress-react.esm-bundler' {
  declare module.exports: any
}

declare module 'cypress/react18/dist/cypress-react.cjs' {
  declare module.exports: any
}

declare module 'cypress/react18/dist/cypress-react.esm-bundler' {
  declare module.exports: any
}

declare module 'cypress/vue/dist/cypress-vue.cjs' {
  declare module.exports: any
}

declare module 'cypress/vue/dist/cypress-vue.esm-bundler' {
  declare module.exports: any
}

declare module 'cypress/vue2/dist/cypress-vue2.browser' {
  declare module.exports: any
}

declare module 'cypress/vue2/dist/cypress-vue2.cjs' {
  declare module.exports: any
}

declare module 'cypress/vue2/dist/cypress-vue2.esm-bundler' {
  declare module.exports: any
}

// Filename aliases
declare module 'cypress/angular/dist/index' {
  declare module.exports: $Exports<'cypress/angular/dist'>
}
declare module 'cypress/angular/dist/index.js' {
  declare module.exports: $Exports<'cypress/angular/dist'>
}
declare module 'cypress/index' {
  declare module.exports: $Exports<'cypress'>
}
declare module 'cypress/index.js' {
  declare module.exports: $Exports<'cypress'>
}
declare module 'cypress/lib/cli.js' {
  declare module.exports: $Exports<'cypress/lib/cli'>
}
declare module 'cypress/lib/cypress.js' {
  declare module.exports: $Exports<'cypress/lib/cypress'>
}
declare module 'cypress/lib/errors.js' {
  declare module.exports: $Exports<'cypress/lib/errors'>
}
declare module 'cypress/lib/exec/info.js' {
  declare module.exports: $Exports<'cypress/lib/exec/info'>
}
declare module 'cypress/lib/exec/open.js' {
  declare module.exports: $Exports<'cypress/lib/exec/open'>
}
declare module 'cypress/lib/exec/run.js' {
  declare module.exports: $Exports<'cypress/lib/exec/run'>
}
declare module 'cypress/lib/exec/shared.js' {
  declare module.exports: $Exports<'cypress/lib/exec/shared'>
}
declare module 'cypress/lib/exec/spawn.js' {
  declare module.exports: $Exports<'cypress/lib/exec/spawn'>
}
declare module 'cypress/lib/exec/versions.js' {
  declare module.exports: $Exports<'cypress/lib/exec/versions'>
}
declare module 'cypress/lib/exec/xvfb.js' {
  declare module.exports: $Exports<'cypress/lib/exec/xvfb'>
}
declare module 'cypress/lib/fs.js' {
  declare module.exports: $Exports<'cypress/lib/fs'>
}
declare module 'cypress/lib/logger.js' {
  declare module.exports: $Exports<'cypress/lib/logger'>
}
declare module 'cypress/lib/tasks/cache.js' {
  declare module.exports: $Exports<'cypress/lib/tasks/cache'>
}
declare module 'cypress/lib/tasks/download.js' {
  declare module.exports: $Exports<'cypress/lib/tasks/download'>
}
declare module 'cypress/lib/tasks/get-folder-size.js' {
  declare module.exports: $Exports<'cypress/lib/tasks/get-folder-size'>
}
declare module 'cypress/lib/tasks/install.js' {
  declare module.exports: $Exports<'cypress/lib/tasks/install'>
}
declare module 'cypress/lib/tasks/state.js' {
  declare module.exports: $Exports<'cypress/lib/tasks/state'>
}
declare module 'cypress/lib/tasks/unzip.js' {
  declare module.exports: $Exports<'cypress/lib/tasks/unzip'>
}
declare module 'cypress/lib/tasks/verify.js' {
  declare module.exports: $Exports<'cypress/lib/tasks/verify'>
}
declare module 'cypress/lib/util.js' {
  declare module.exports: $Exports<'cypress/lib/util'>
}
declare module 'cypress/lib/VerboseRenderer.js' {
  declare module.exports: $Exports<'cypress/lib/VerboseRenderer'>
}
declare module 'cypress/mount-utils/dist/index' {
  declare module.exports: $Exports<'cypress/mount-utils/dist'>
}
declare module 'cypress/mount-utils/dist/index.js' {
  declare module.exports: $Exports<'cypress/mount-utils/dist'>
}
declare module 'cypress/react/dist/cypress-react.cjs.js' {
  declare module.exports: $Exports<'cypress/react/dist/cypress-react.cjs'>
}
declare module 'cypress/react/dist/cypress-react.esm-bundler.js' {
  declare module.exports: $Exports<'cypress/react/dist/cypress-react.esm-bundler'>
}
declare module 'cypress/react18/dist/cypress-react.cjs.js' {
  declare module.exports: $Exports<'cypress/react18/dist/cypress-react.cjs'>
}
declare module 'cypress/react18/dist/cypress-react.esm-bundler.js' {
  declare module.exports: $Exports<'cypress/react18/dist/cypress-react.esm-bundler'>
}
declare module 'cypress/vue/dist/cypress-vue.cjs.js' {
  declare module.exports: $Exports<'cypress/vue/dist/cypress-vue.cjs'>
}
declare module 'cypress/vue/dist/cypress-vue.esm-bundler.js' {
  declare module.exports: $Exports<'cypress/vue/dist/cypress-vue.esm-bundler'>
}
declare module 'cypress/vue2/dist/cypress-vue2.browser.js' {
  declare module.exports: $Exports<'cypress/vue2/dist/cypress-vue2.browser'>
}
declare module 'cypress/vue2/dist/cypress-vue2.cjs.js' {
  declare module.exports: $Exports<'cypress/vue2/dist/cypress-vue2.cjs'>
}
declare module 'cypress/vue2/dist/cypress-vue2.esm-bundler.js' {
  declare module.exports: $Exports<'cypress/vue2/dist/cypress-vue2.esm-bundler'>
}
