// flow-typed signature: d43bee3d9ab2e6ee6ec54cfc7e2328fa
// flow-typed version: <<STUB>>/delta-e_v0.0.7/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'delta-e'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'delta-e' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'delta-e/dist/deltae.global.min' {
  declare module.exports: any;
}

declare module 'delta-e/gulpfile' {
  declare module.exports: any;
}

declare module 'delta-e/src/dE00' {
  declare module.exports: any;
}

declare module 'delta-e/src/dE76' {
  declare module.exports: any;
}

declare module 'delta-e/src/dE94' {
  declare module.exports: any;
}

declare module 'delta-e/src' {
  declare module.exports: any;
}

declare module 'delta-e/tests/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'delta-e/dist/deltae.global.min.js' {
  declare module.exports: $Exports<'delta-e/dist/deltae.global.min'>;
}
declare module 'delta-e/gulpfile.js' {
  declare module.exports: $Exports<'delta-e/gulpfile'>;
}
declare module 'delta-e/src/dE00.js' {
  declare module.exports: $Exports<'delta-e/src/dE00'>;
}
declare module 'delta-e/src/dE76.js' {
  declare module.exports: $Exports<'delta-e/src/dE76'>;
}
declare module 'delta-e/src/dE94.js' {
  declare module.exports: $Exports<'delta-e/src/dE94'>;
}
declare module 'delta-e/src/index' {
  declare module.exports: $Exports<'delta-e/src'>;
}
declare module 'delta-e/src/index.js' {
  declare module.exports: $Exports<'delta-e/src'>;
}
declare module 'delta-e/tests/main.js' {
  declare module.exports: $Exports<'delta-e/tests/main'>;
}
