// flow-typed signature: 7b299947607d7fa7355a53c2a38c61d8
// flow-typed version: <<STUB>>/dotenv_v16.0.1/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dotenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dotenv' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dotenv/config' {
  declare module.exports: any
}

declare module 'dotenv/lib/cli-options' {
  declare module.exports: any
}

declare module 'dotenv/lib/env-options' {
  declare module.exports: any
}

declare module 'dotenv/lib/main' {
  declare module.exports: any
}

// Filename aliases
declare module 'dotenv/config.js' {
  declare module.exports: $Exports<'dotenv/config'>
}
declare module 'dotenv/lib/cli-options.js' {
  declare module.exports: $Exports<'dotenv/lib/cli-options'>
}
declare module 'dotenv/lib/env-options.js' {
  declare module.exports: $Exports<'dotenv/lib/env-options'>
}
declare module 'dotenv/lib/main.js' {
  declare module.exports: $Exports<'dotenv/lib/main'>
}
