// flow-typed signature: f5fd86b5348d5aaaaa802982dc022b66
// flow-typed version: <<STUB>>/ejs-html-loader_v4.0.1/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ejs-html-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ejs-html-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ejs-html-loader/lib/cache' {
  declare module.exports: any;
}

declare module 'ejs-html-loader/lib' {
  declare module.exports: any;
}

declare module 'ejs-html-loader/lib/render' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ejs-html-loader/lib/cache.js' {
  declare module.exports: $Exports<'ejs-html-loader/lib/cache'>;
}
declare module 'ejs-html-loader/lib/index' {
  declare module.exports: $Exports<'ejs-html-loader/lib'>;
}
declare module 'ejs-html-loader/lib/index.js' {
  declare module.exports: $Exports<'ejs-html-loader/lib'>;
}
declare module 'ejs-html-loader/lib/render.js' {
  declare module.exports: $Exports<'ejs-html-loader/lib/render'>;
}
