// flow-typed signature: 12a436f4443ed368b3bc01fc794b0975
// flow-typed version: <<STUB>>/eslint-webpack-plugin_v3.2.0/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-webpack-plugin' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-webpack-plugin/dist/ESLintError' {
  declare module.exports: any
}

declare module 'eslint-webpack-plugin/dist/getESLint' {
  declare module.exports: any
}

declare module 'eslint-webpack-plugin/dist' {
  declare module.exports: any
}

declare module 'eslint-webpack-plugin/dist/linter' {
  declare module.exports: any
}

declare module 'eslint-webpack-plugin/dist/options' {
  declare module.exports: any
}

declare module 'eslint-webpack-plugin/dist/utils' {
  declare module.exports: any
}

declare module 'eslint-webpack-plugin/dist/worker' {
  declare module.exports: any
}

// Filename aliases
declare module 'eslint-webpack-plugin/dist/ESLintError.js' {
  declare module.exports: $Exports<'eslint-webpack-plugin/dist/ESLintError'>
}
declare module 'eslint-webpack-plugin/dist/getESLint.js' {
  declare module.exports: $Exports<'eslint-webpack-plugin/dist/getESLint'>
}
declare module 'eslint-webpack-plugin/dist/index' {
  declare module.exports: $Exports<'eslint-webpack-plugin/dist'>
}
declare module 'eslint-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'eslint-webpack-plugin/dist'>
}
declare module 'eslint-webpack-plugin/dist/linter.js' {
  declare module.exports: $Exports<'eslint-webpack-plugin/dist/linter'>
}
declare module 'eslint-webpack-plugin/dist/options.js' {
  declare module.exports: $Exports<'eslint-webpack-plugin/dist/options'>
}
declare module 'eslint-webpack-plugin/dist/utils.js' {
  declare module.exports: $Exports<'eslint-webpack-plugin/dist/utils'>
}
declare module 'eslint-webpack-plugin/dist/worker.js' {
  declare module.exports: $Exports<'eslint-webpack-plugin/dist/worker'>
}
