// flow-typed signature: c82b38601c6d4c83a85dd2c668c88895
// flow-typed version: <<STUB>>/eslint-plugin-formatjs_v2.3.13/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-formatjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-formatjs' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-formatjs/dist' {
  declare module.exports: any
}

declare module 'eslint-plugin-formatjs/dist/rules/blacklist-elements' {
  declare module.exports: any
}

declare module 'eslint-plugin-formatjs/dist/rules/enforce-default-message' {
  declare module.exports: any
}

declare module 'eslint-plugin-formatjs/dist/rules/enforce-description' {
  declare module.exports: any
}

declare module 'eslint-plugin-formatjs/dist/rules/enforce-placeholders' {
  declare module.exports: any
}

declare module 'eslint-plugin-formatjs/dist/rules/enforce-plural-rules' {
  declare module.exports: any
}

declare module 'eslint-plugin-formatjs/dist/rules/no-camel-case' {
  declare module.exports: any
}

declare module 'eslint-plugin-formatjs/dist/rules/no-emoji' {
  declare module.exports: any
}

declare module 'eslint-plugin-formatjs/dist/rules/no-id' {
  declare module.exports: any
}

declare module 'eslint-plugin-formatjs/dist/rules/no-multiple-plurals' {
  declare module.exports: any
}

declare module 'eslint-plugin-formatjs/dist/rules/no-multiple-whitespaces' {
  declare module.exports: any
}

declare module 'eslint-plugin-formatjs/dist/rules/no-offset' {
  declare module.exports: any
}

declare module 'eslint-plugin-formatjs/dist/rules/supported-datetime-skeleton' {
  declare module.exports: any
}

declare module 'eslint-plugin-formatjs/dist/util' {
  declare module.exports: any
}

// Filename aliases
declare module 'eslint-plugin-formatjs/dist/index' {
  declare module.exports: $Exports<'eslint-plugin-formatjs/dist'>
}
declare module 'eslint-plugin-formatjs/dist/index.js' {
  declare module.exports: $Exports<'eslint-plugin-formatjs/dist'>
}
declare module 'eslint-plugin-formatjs/dist/rules/blacklist-elements.js' {
  declare module.exports: $Exports<'eslint-plugin-formatjs/dist/rules/blacklist-elements'>
}
declare module 'eslint-plugin-formatjs/dist/rules/enforce-default-message.js' {
  declare module.exports: $Exports<'eslint-plugin-formatjs/dist/rules/enforce-default-message'>
}
declare module 'eslint-plugin-formatjs/dist/rules/enforce-description.js' {
  declare module.exports: $Exports<'eslint-plugin-formatjs/dist/rules/enforce-description'>
}
declare module 'eslint-plugin-formatjs/dist/rules/enforce-placeholders.js' {
  declare module.exports: $Exports<'eslint-plugin-formatjs/dist/rules/enforce-placeholders'>
}
declare module 'eslint-plugin-formatjs/dist/rules/enforce-plural-rules.js' {
  declare module.exports: $Exports<'eslint-plugin-formatjs/dist/rules/enforce-plural-rules'>
}
declare module 'eslint-plugin-formatjs/dist/rules/no-camel-case.js' {
  declare module.exports: $Exports<'eslint-plugin-formatjs/dist/rules/no-camel-case'>
}
declare module 'eslint-plugin-formatjs/dist/rules/no-emoji.js' {
  declare module.exports: $Exports<'eslint-plugin-formatjs/dist/rules/no-emoji'>
}
declare module 'eslint-plugin-formatjs/dist/rules/no-id.js' {
  declare module.exports: $Exports<'eslint-plugin-formatjs/dist/rules/no-id'>
}
declare module 'eslint-plugin-formatjs/dist/rules/no-multiple-plurals.js' {
  declare module.exports: $Exports<'eslint-plugin-formatjs/dist/rules/no-multiple-plurals'>
}
declare module 'eslint-plugin-formatjs/dist/rules/no-multiple-whitespaces.js' {
  declare module.exports: $Exports<'eslint-plugin-formatjs/dist/rules/no-multiple-whitespaces'>
}
declare module 'eslint-plugin-formatjs/dist/rules/no-offset.js' {
  declare module.exports: $Exports<'eslint-plugin-formatjs/dist/rules/no-offset'>
}
declare module 'eslint-plugin-formatjs/dist/rules/supported-datetime-skeleton.js' {
  declare module.exports: $Exports<'eslint-plugin-formatjs/dist/rules/supported-datetime-skeleton'>
}
declare module 'eslint-plugin-formatjs/dist/util.js' {
  declare module.exports: $Exports<'eslint-plugin-formatjs/dist/util'>
}
