// flow-typed signature: 095a0d4c152cd062aa6c1bced8a92980
// flow-typed version: <<STUB>>/eslint-plugin-n_v^15.2.4/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-n' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-n/lib/configs/_commons' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/configs/recommended-module' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/configs/recommended-script' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/configs/recommended' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/converted-esm/import-meta-resolve' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/callback-return' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/exports-style' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/file-extension-in-import' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/global-require' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/handle-callback-err' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-callback-literal' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-deprecated-api' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-exports-assign' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-extraneous-import' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-extraneous-require' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-hide-core-modules' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-missing-import' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-missing-require' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-mixed-requires' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-new-require' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-path-concat' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-process-env' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-process-exit' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-restricted-import' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-restricted-require' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-sync' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-unpublished-bin' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-unpublished-import' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-unpublished-require' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-unsupported-features' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-unsupported-features/es-builtins' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-unsupported-features/es-syntax' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/no-unsupported-features/node-builtins' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/prefer-global/buffer' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/prefer-global/console' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/prefer-global/process' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/prefer-global/text-decoder' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/prefer-global/text-encoder' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/prefer-global/url-search-params' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/prefer-global/url' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/prefer-promises/dns' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/prefer-promises/fs' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/process-exit-as-throw' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/rules/shebang' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/cache' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/check-existence' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/check-extraneous' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/check-prefer-global' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/check-publish' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/check-restricted' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/check-unsupported-builtins' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/enumerate-property-names' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/exists' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/get-allow-modules' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/get-configured-node-version' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/get-convert-path' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/get-npmignore' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/get-package-json' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/get-resolve-paths' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/get-semver-range' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/get-try-extensions' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/import-target' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/is-typescript' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/map-typescript-extension' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/merge-visitors-in-place' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/strip-import-path-params' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/visit-import' {
  declare module.exports: any
}

declare module 'eslint-plugin-n/lib/util/visit-require' {
  declare module.exports: any
}

// Filename aliases
declare module 'eslint-plugin-n/lib/configs/_commons.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/configs/_commons'>
}
declare module 'eslint-plugin-n/lib/configs/recommended-module.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/configs/recommended-module'>
}
declare module 'eslint-plugin-n/lib/configs/recommended-script.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/configs/recommended-script'>
}
declare module 'eslint-plugin-n/lib/configs/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/configs/recommended'>
}
declare module 'eslint-plugin-n/lib/converted-esm/import-meta-resolve.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/converted-esm/import-meta-resolve'>
}
declare module 'eslint-plugin-n/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-n/lib'>
}
declare module 'eslint-plugin-n/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib'>
}
declare module 'eslint-plugin-n/lib/rules/callback-return.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/callback-return'>
}
declare module 'eslint-plugin-n/lib/rules/exports-style.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/exports-style'>
}
declare module 'eslint-plugin-n/lib/rules/file-extension-in-import.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/file-extension-in-import'>
}
declare module 'eslint-plugin-n/lib/rules/global-require.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/global-require'>
}
declare module 'eslint-plugin-n/lib/rules/handle-callback-err.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/handle-callback-err'>
}
declare module 'eslint-plugin-n/lib/rules/no-callback-literal.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-callback-literal'>
}
declare module 'eslint-plugin-n/lib/rules/no-deprecated-api.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-deprecated-api'>
}
declare module 'eslint-plugin-n/lib/rules/no-exports-assign.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-exports-assign'>
}
declare module 'eslint-plugin-n/lib/rules/no-extraneous-import.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-extraneous-import'>
}
declare module 'eslint-plugin-n/lib/rules/no-extraneous-require.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-extraneous-require'>
}
declare module 'eslint-plugin-n/lib/rules/no-hide-core-modules.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-hide-core-modules'>
}
declare module 'eslint-plugin-n/lib/rules/no-missing-import.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-missing-import'>
}
declare module 'eslint-plugin-n/lib/rules/no-missing-require.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-missing-require'>
}
declare module 'eslint-plugin-n/lib/rules/no-mixed-requires.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-mixed-requires'>
}
declare module 'eslint-plugin-n/lib/rules/no-new-require.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-new-require'>
}
declare module 'eslint-plugin-n/lib/rules/no-path-concat.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-path-concat'>
}
declare module 'eslint-plugin-n/lib/rules/no-process-env.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-process-env'>
}
declare module 'eslint-plugin-n/lib/rules/no-process-exit.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-process-exit'>
}
declare module 'eslint-plugin-n/lib/rules/no-restricted-import.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-restricted-import'>
}
declare module 'eslint-plugin-n/lib/rules/no-restricted-require.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-restricted-require'>
}
declare module 'eslint-plugin-n/lib/rules/no-sync.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-sync'>
}
declare module 'eslint-plugin-n/lib/rules/no-unpublished-bin.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-unpublished-bin'>
}
declare module 'eslint-plugin-n/lib/rules/no-unpublished-import.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-unpublished-import'>
}
declare module 'eslint-plugin-n/lib/rules/no-unpublished-require.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-unpublished-require'>
}
declare module 'eslint-plugin-n/lib/rules/no-unsupported-features.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-unsupported-features'>
}
declare module 'eslint-plugin-n/lib/rules/no-unsupported-features/es-builtins.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-unsupported-features/es-builtins'>
}
declare module 'eslint-plugin-n/lib/rules/no-unsupported-features/es-syntax.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-unsupported-features/es-syntax'>
}
declare module 'eslint-plugin-n/lib/rules/no-unsupported-features/node-builtins.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/no-unsupported-features/node-builtins'>
}
declare module 'eslint-plugin-n/lib/rules/prefer-global/buffer.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/prefer-global/buffer'>
}
declare module 'eslint-plugin-n/lib/rules/prefer-global/console.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/prefer-global/console'>
}
declare module 'eslint-plugin-n/lib/rules/prefer-global/process.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/prefer-global/process'>
}
declare module 'eslint-plugin-n/lib/rules/prefer-global/text-decoder.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/prefer-global/text-decoder'>
}
declare module 'eslint-plugin-n/lib/rules/prefer-global/text-encoder.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/prefer-global/text-encoder'>
}
declare module 'eslint-plugin-n/lib/rules/prefer-global/url-search-params.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/prefer-global/url-search-params'>
}
declare module 'eslint-plugin-n/lib/rules/prefer-global/url.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/prefer-global/url'>
}
declare module 'eslint-plugin-n/lib/rules/prefer-promises/dns.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/prefer-promises/dns'>
}
declare module 'eslint-plugin-n/lib/rules/prefer-promises/fs.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/prefer-promises/fs'>
}
declare module 'eslint-plugin-n/lib/rules/process-exit-as-throw.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/process-exit-as-throw'>
}
declare module 'eslint-plugin-n/lib/rules/shebang.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/rules/shebang'>
}
declare module 'eslint-plugin-n/lib/util/cache.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/cache'>
}
declare module 'eslint-plugin-n/lib/util/check-existence.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/check-existence'>
}
declare module 'eslint-plugin-n/lib/util/check-extraneous.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/check-extraneous'>
}
declare module 'eslint-plugin-n/lib/util/check-prefer-global.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/check-prefer-global'>
}
declare module 'eslint-plugin-n/lib/util/check-publish.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/check-publish'>
}
declare module 'eslint-plugin-n/lib/util/check-restricted.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/check-restricted'>
}
declare module 'eslint-plugin-n/lib/util/check-unsupported-builtins.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/check-unsupported-builtins'>
}
declare module 'eslint-plugin-n/lib/util/enumerate-property-names.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/enumerate-property-names'>
}
declare module 'eslint-plugin-n/lib/util/exists.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/exists'>
}
declare module 'eslint-plugin-n/lib/util/get-allow-modules.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/get-allow-modules'>
}
declare module 'eslint-plugin-n/lib/util/get-configured-node-version.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/get-configured-node-version'>
}
declare module 'eslint-plugin-n/lib/util/get-convert-path.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/get-convert-path'>
}
declare module 'eslint-plugin-n/lib/util/get-npmignore.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/get-npmignore'>
}
declare module 'eslint-plugin-n/lib/util/get-package-json.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/get-package-json'>
}
declare module 'eslint-plugin-n/lib/util/get-resolve-paths.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/get-resolve-paths'>
}
declare module 'eslint-plugin-n/lib/util/get-semver-range.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/get-semver-range'>
}
declare module 'eslint-plugin-n/lib/util/get-try-extensions.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/get-try-extensions'>
}
declare module 'eslint-plugin-n/lib/util/import-target.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/import-target'>
}
declare module 'eslint-plugin-n/lib/util/is-typescript.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/is-typescript'>
}
declare module 'eslint-plugin-n/lib/util/map-typescript-extension.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/map-typescript-extension'>
}
declare module 'eslint-plugin-n/lib/util/merge-visitors-in-place.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/merge-visitors-in-place'>
}
declare module 'eslint-plugin-n/lib/util/strip-import-path-params.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/strip-import-path-params'>
}
declare module 'eslint-plugin-n/lib/util/visit-import.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/visit-import'>
}
declare module 'eslint-plugin-n/lib/util/visit-require.js' {
  declare module.exports: $Exports<'eslint-plugin-n/lib/util/visit-require'>
}
