// flow-typed signature: d7702908ab33d0d7d7c87fe9350b7c3b
// flow-typed version: <<STUB>>/floodfill_v2.1.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'floodfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'floodfill' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'floodfill/floodfill' {
  declare module.exports: any
}

declare module 'floodfill/floodfill.min' {
  declare module.exports: any
}

// Filename aliases
declare module 'floodfill/floodfill.js' {
  declare module.exports: $Exports<'floodfill/floodfill'>
}
declare module 'floodfill/floodfill.min.js' {
  declare module.exports: $Exports<'floodfill/floodfill.min'>
}
