// flow-typed signature: 05209eff136003955c0032ab1a193508
// flow-typed version: <<STUB>>/focus-within-polyfill_v5.0.9/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'focus-within-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'focus-within-polyfill' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'focus-within-polyfill/dist/focus-within-polyfill' {
  declare module.exports: any
}

declare module 'focus-within-polyfill/src/focus-within' {
  declare module.exports: any
}

// Filename aliases
declare module 'focus-within-polyfill/dist/focus-within-polyfill.js' {
  declare module.exports: $Exports<'focus-within-polyfill/dist/focus-within-polyfill'>
}
declare module 'focus-within-polyfill/src/focus-within.js' {
  declare module.exports: $Exports<'focus-within-polyfill/src/focus-within'>
}
