// flow-typed signature: b75411c008eddd0032a70864b38d0386
// flow-typed version: <<STUB>>/glob-move_v1.0.1/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glob-move'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glob-move' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'glob-move/index' {
  declare module.exports: $Exports<'glob-move'>
}
declare module 'glob-move/index.js' {
  declare module.exports: $Exports<'glob-move'>
}
