// flow-typed signature: 11dc9ebd83b4588f35f406f5a0329de0
// flow-typed version: <<STUB>>/jest-puppeteer_v^4.4.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-puppeteer' {
  declare module.exports: any
}
