// flow-typed signature: 4a711ba694595e79f15c4f4928cd1b54
// flow-typed version: <<STUB>>/ml5_v0.2.3/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ml5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ml5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ml5/dist/ml5.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ml5/dist/ml5.min.js' {
  declare module.exports: $Exports<'ml5/dist/ml5.min'>;
}
