// flow-typed signature: 2ca95daaf6f94ea633fb43349754309e
// flow-typed version: <<STUB>>/node-sass-utils_v1.1.3/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-sass-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-sass-utils' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-sass-utils/build/lint' {
  declare module.exports: any
}

declare module 'node-sass-utils/build/test' {
  declare module.exports: any
}

declare module 'node-sass-utils/Gruntfile' {
  declare module.exports: any
}

declare module 'node-sass-utils/gulpfile' {
  declare module.exports: any
}

declare module 'node-sass-utils/lib/coercion' {
  declare module.exports: any
}

declare module 'node-sass-utils/lib' {
  declare module.exports: any
}

declare module 'node-sass-utils/lib/sass_dimension' {
  declare module.exports: any
}

declare module 'node-sass-utils/lib/sass_js_map' {
  declare module.exports: any
}

declare module 'node-sass-utils/test/test_coercion' {
  declare module.exports: any
}

declare module 'node-sass-utils/test/test_infection' {
  declare module.exports: any
}

declare module 'node-sass-utils/test/test_sass_dimension' {
  declare module.exports: any
}

declare module 'node-sass-utils/test/test_sass_js_map' {
  declare module.exports: any
}

declare module 'node-sass-utils/test/test_sass_utils' {
  declare module.exports: any
}

declare module 'node-sass-utils/test/testutils' {
  declare module.exports: any
}

// Filename aliases
declare module 'node-sass-utils/build/lint.js' {
  declare module.exports: $Exports<'node-sass-utils/build/lint'>
}
declare module 'node-sass-utils/build/test.js' {
  declare module.exports: $Exports<'node-sass-utils/build/test'>
}
declare module 'node-sass-utils/Gruntfile.js' {
  declare module.exports: $Exports<'node-sass-utils/Gruntfile'>
}
declare module 'node-sass-utils/gulpfile.js' {
  declare module.exports: $Exports<'node-sass-utils/gulpfile'>
}
declare module 'node-sass-utils/lib/coercion.js' {
  declare module.exports: $Exports<'node-sass-utils/lib/coercion'>
}
declare module 'node-sass-utils/lib/index' {
  declare module.exports: $Exports<'node-sass-utils/lib'>
}
declare module 'node-sass-utils/lib/index.js' {
  declare module.exports: $Exports<'node-sass-utils/lib'>
}
declare module 'node-sass-utils/lib/sass_dimension.js' {
  declare module.exports: $Exports<'node-sass-utils/lib/sass_dimension'>
}
declare module 'node-sass-utils/lib/sass_js_map.js' {
  declare module.exports: $Exports<'node-sass-utils/lib/sass_js_map'>
}
declare module 'node-sass-utils/test/test_coercion.js' {
  declare module.exports: $Exports<'node-sass-utils/test/test_coercion'>
}
declare module 'node-sass-utils/test/test_infection.js' {
  declare module.exports: $Exports<'node-sass-utils/test/test_infection'>
}
declare module 'node-sass-utils/test/test_sass_dimension.js' {
  declare module.exports: $Exports<'node-sass-utils/test/test_sass_dimension'>
}
declare module 'node-sass-utils/test/test_sass_js_map.js' {
  declare module.exports: $Exports<'node-sass-utils/test/test_sass_js_map'>
}
declare module 'node-sass-utils/test/test_sass_utils.js' {
  declare module.exports: $Exports<'node-sass-utils/test/test_sass_utils'>
}
declare module 'node-sass-utils/test/testutils.js' {
  declare module.exports: $Exports<'node-sass-utils/test/testutils'>
}
