// flow-typed signature: d1ec7cf343052371158877b58ea459ff
// flow-typed version: <<STUB>>/npm-force-resolutions_v0.0.3/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-force-resolutions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-force-resolutions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-force-resolutions/out/AEF573C' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/BAB852C' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/cljs_deps' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/cljs/core' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/cljs/nodejs' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/clojure/string' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/cognitect/transit' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/com/cognitect/transit' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/com/cognitect/transit/caching' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/com/cognitect/transit/delimiters' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/com/cognitect/transit/eq' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/com/cognitect/transit/handlers' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/com/cognitect/transit/impl/decoder' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/com/cognitect/transit/impl/reader' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/com/cognitect/transit/impl/writer' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/com/cognitect/transit/types' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/com/cognitect/transit/util' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/array/array' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/asserts/asserts' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/base' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/bootstrap/nodejs' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/debug/error' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/deps' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/dom/nodetype' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/functions/functions' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/iter/iter' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/math/integer' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/math/long' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/math/math' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/object/object' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/reflect/reflect' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/string/string' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/string/stringbuffer' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/structs/map' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/structs/structs' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/uri/uri' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/goog/uri/utils' {
  declare module.exports: any;
}

declare module 'npm-force-resolutions/out/npm_force_resolutions/core' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-force-resolutions/index' {
  declare module.exports: $Exports<'npm-force-resolutions'>;
}
declare module 'npm-force-resolutions/index.js' {
  declare module.exports: $Exports<'npm-force-resolutions'>;
}
declare module 'npm-force-resolutions/out/AEF573C.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/AEF573C'>;
}
declare module 'npm-force-resolutions/out/BAB852C.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/BAB852C'>;
}
declare module 'npm-force-resolutions/out/cljs_deps.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/cljs_deps'>;
}
declare module 'npm-force-resolutions/out/cljs/core.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/cljs/core'>;
}
declare module 'npm-force-resolutions/out/cljs/nodejs.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/cljs/nodejs'>;
}
declare module 'npm-force-resolutions/out/clojure/string.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/clojure/string'>;
}
declare module 'npm-force-resolutions/out/cognitect/transit.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/cognitect/transit'>;
}
declare module 'npm-force-resolutions/out/com/cognitect/transit.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/com/cognitect/transit'>;
}
declare module 'npm-force-resolutions/out/com/cognitect/transit/caching.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/com/cognitect/transit/caching'>;
}
declare module 'npm-force-resolutions/out/com/cognitect/transit/delimiters.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/com/cognitect/transit/delimiters'>;
}
declare module 'npm-force-resolutions/out/com/cognitect/transit/eq.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/com/cognitect/transit/eq'>;
}
declare module 'npm-force-resolutions/out/com/cognitect/transit/handlers.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/com/cognitect/transit/handlers'>;
}
declare module 'npm-force-resolutions/out/com/cognitect/transit/impl/decoder.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/com/cognitect/transit/impl/decoder'>;
}
declare module 'npm-force-resolutions/out/com/cognitect/transit/impl/reader.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/com/cognitect/transit/impl/reader'>;
}
declare module 'npm-force-resolutions/out/com/cognitect/transit/impl/writer.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/com/cognitect/transit/impl/writer'>;
}
declare module 'npm-force-resolutions/out/com/cognitect/transit/types.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/com/cognitect/transit/types'>;
}
declare module 'npm-force-resolutions/out/com/cognitect/transit/util.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/com/cognitect/transit/util'>;
}
declare module 'npm-force-resolutions/out/goog/array/array.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/array/array'>;
}
declare module 'npm-force-resolutions/out/goog/asserts/asserts.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/asserts/asserts'>;
}
declare module 'npm-force-resolutions/out/goog/base.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/base'>;
}
declare module 'npm-force-resolutions/out/goog/bootstrap/nodejs.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/bootstrap/nodejs'>;
}
declare module 'npm-force-resolutions/out/goog/debug/error.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/debug/error'>;
}
declare module 'npm-force-resolutions/out/goog/deps.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/deps'>;
}
declare module 'npm-force-resolutions/out/goog/dom/nodetype.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/dom/nodetype'>;
}
declare module 'npm-force-resolutions/out/goog/functions/functions.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/functions/functions'>;
}
declare module 'npm-force-resolutions/out/goog/iter/iter.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/iter/iter'>;
}
declare module 'npm-force-resolutions/out/goog/math/integer.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/math/integer'>;
}
declare module 'npm-force-resolutions/out/goog/math/long.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/math/long'>;
}
declare module 'npm-force-resolutions/out/goog/math/math.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/math/math'>;
}
declare module 'npm-force-resolutions/out/goog/object/object.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/object/object'>;
}
declare module 'npm-force-resolutions/out/goog/reflect/reflect.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/reflect/reflect'>;
}
declare module 'npm-force-resolutions/out/goog/string/string.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/string/string'>;
}
declare module 'npm-force-resolutions/out/goog/string/stringbuffer.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/string/stringbuffer'>;
}
declare module 'npm-force-resolutions/out/goog/structs/map.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/structs/map'>;
}
declare module 'npm-force-resolutions/out/goog/structs/structs.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/structs/structs'>;
}
declare module 'npm-force-resolutions/out/goog/uri/uri.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/uri/uri'>;
}
declare module 'npm-force-resolutions/out/goog/uri/utils.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/goog/uri/utils'>;
}
declare module 'npm-force-resolutions/out/npm_force_resolutions/core.js' {
  declare module.exports: $Exports<'npm-force-resolutions/out/npm_force_resolutions/core'>;
}
