// flow-typed signature: bcb123d3a513367f82a7d7491de95713
// flow-typed version: <<STUB>>/object-hash_v2.0.3/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object-hash/dist/object_hash' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object-hash/dist/object_hash.js' {
  declare module.exports: $Exports<'object-hash/dist/object_hash'>;
}
declare module 'object-hash/index' {
  declare module.exports: $Exports<'object-hash'>;
}
declare module 'object-hash/index.js' {
  declare module.exports: $Exports<'object-hash'>;
}
