// flow-typed signature: 9d8772d80ed7105d4ac949a964554c86
// flow-typed version: <<STUB>>/postcss-wrapper-loader_v1.0.2/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-wrapper-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-wrapper-loader' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'postcss-wrapper-loader/index' {
  declare module.exports: $Exports<'postcss-wrapper-loader'>
}
declare module 'postcss-wrapper-loader/index.js' {
  declare module.exports: $Exports<'postcss-wrapper-loader'>
}
