// flow-typed signature: 44e92b757dc46f09457e9658eac542f5
// flow-typed version: <<STUB>>/postcss-prefixwrap_v1.31.0/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-prefixwrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-prefixwrap' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-prefixwrap/build' {
  declare module.exports: any
}

declare module 'postcss-prefixwrap/build/indexWrap' {
  declare module.exports: any
}

declare module 'postcss-prefixwrap/build/indexWrap.spec' {
  declare module.exports: any
}

declare module 'postcss-prefixwrap/build/PostCSSPrefixWrap' {
  declare module.exports: any
}

declare module 'postcss-prefixwrap/build/PostCSSPrefixWrap.spec' {
  declare module.exports: any
}

declare module 'postcss-prefixwrap/build/Selector' {
  declare module.exports: any
}

declare module 'postcss-prefixwrap/build/Selector.spec' {
  declare module.exports: any
}

declare module 'postcss-prefixwrap/build/Types' {
  declare module.exports: any
}

// Filename aliases
declare module 'postcss-prefixwrap/build/index' {
  declare module.exports: $Exports<'postcss-prefixwrap/build'>
}
declare module 'postcss-prefixwrap/build/index.js' {
  declare module.exports: $Exports<'postcss-prefixwrap/build'>
}
declare module 'postcss-prefixwrap/build/indexWrap.js' {
  declare module.exports: $Exports<'postcss-prefixwrap/build/indexWrap'>
}
declare module 'postcss-prefixwrap/build/indexWrap.spec.js' {
  declare module.exports: $Exports<'postcss-prefixwrap/build/indexWrap.spec'>
}
declare module 'postcss-prefixwrap/build/PostCSSPrefixWrap.js' {
  declare module.exports: $Exports<'postcss-prefixwrap/build/PostCSSPrefixWrap'>
}
declare module 'postcss-prefixwrap/build/PostCSSPrefixWrap.spec.js' {
  declare module.exports: $Exports<'postcss-prefixwrap/build/PostCSSPrefixWrap.spec'>
}
declare module 'postcss-prefixwrap/build/Selector.js' {
  declare module.exports: $Exports<'postcss-prefixwrap/build/Selector'>
}
declare module 'postcss-prefixwrap/build/Selector.spec.js' {
  declare module.exports: $Exports<'postcss-prefixwrap/build/Selector.spec'>
}
declare module 'postcss-prefixwrap/build/Types.js' {
  declare module.exports: $Exports<'postcss-prefixwrap/build/Types'>
}
