// flow-typed signature: 0b0fe91522195d3dc727fb4734efe81d
// flow-typed version: <<STUB>>/postcss-focus-visible_v^7.1.0/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-focus-visible'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-focus-visible' {
  declare module.exports: any
}
