// flow-typed signature: 2a9c0d4f39bb4336a966a117d1e087f7
// flow-typed version: <<STUB>>/puppeteer_v3.3.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'puppeteer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'puppeteer/DeviceDescriptors' {
  declare module.exports: any;
}

declare module 'puppeteer/Errors' {
  declare module.exports: any;
}

declare module 'puppeteer/install' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Accessibility' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/api' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Browser' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/BrowserFetcher' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Connection' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/ConnectionTransport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/ConsoleMessage' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Coverage' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/DeviceDescriptors' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Dialog' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/DOMWorld' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/EmulationManager' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Errors' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Events' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/ExecutionContext' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/FileChooser' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/FrameManager' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/helper' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/HTTPRequest' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/HTTPResponse' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Input' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/JSHandle' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Launcher' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/launcher/BrowserRunner' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/launcher/LaunchOptions' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/LifecycleWatcher' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/NetworkManager' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Page' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/PipeTransport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Puppeteer' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/PuppeteerViewport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/QueryHandler' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/SecurityDetails' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Target' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/TimeoutSettings' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Tracing' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/USKeyboardLayout' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/WebSocketTransport' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/WebWorker' {
  declare module.exports: any;
}

declare module 'puppeteer/typescript-if-required' {
  declare module.exports: any;
}

// Filename aliases
declare module 'puppeteer/DeviceDescriptors.js' {
  declare module.exports: $Exports<'puppeteer/DeviceDescriptors'>;
}
declare module 'puppeteer/Errors.js' {
  declare module.exports: $Exports<'puppeteer/Errors'>;
}
declare module 'puppeteer/index' {
  declare module.exports: $Exports<'puppeteer'>;
}
declare module 'puppeteer/index.js' {
  declare module.exports: $Exports<'puppeteer'>;
}
declare module 'puppeteer/install.js' {
  declare module.exports: $Exports<'puppeteer/install'>;
}
declare module 'puppeteer/lib/Accessibility.js' {
  declare module.exports: $Exports<'puppeteer/lib/Accessibility'>;
}
declare module 'puppeteer/lib/api.js' {
  declare module.exports: $Exports<'puppeteer/lib/api'>;
}
declare module 'puppeteer/lib/Browser.js' {
  declare module.exports: $Exports<'puppeteer/lib/Browser'>;
}
declare module 'puppeteer/lib/BrowserFetcher.js' {
  declare module.exports: $Exports<'puppeteer/lib/BrowserFetcher'>;
}
declare module 'puppeteer/lib/Connection.js' {
  declare module.exports: $Exports<'puppeteer/lib/Connection'>;
}
declare module 'puppeteer/lib/ConnectionTransport.js' {
  declare module.exports: $Exports<'puppeteer/lib/ConnectionTransport'>;
}
declare module 'puppeteer/lib/ConsoleMessage.js' {
  declare module.exports: $Exports<'puppeteer/lib/ConsoleMessage'>;
}
declare module 'puppeteer/lib/Coverage.js' {
  declare module.exports: $Exports<'puppeteer/lib/Coverage'>;
}
declare module 'puppeteer/lib/DeviceDescriptors.js' {
  declare module.exports: $Exports<'puppeteer/lib/DeviceDescriptors'>;
}
declare module 'puppeteer/lib/Dialog.js' {
  declare module.exports: $Exports<'puppeteer/lib/Dialog'>;
}
declare module 'puppeteer/lib/DOMWorld.js' {
  declare module.exports: $Exports<'puppeteer/lib/DOMWorld'>;
}
declare module 'puppeteer/lib/EmulationManager.js' {
  declare module.exports: $Exports<'puppeteer/lib/EmulationManager'>;
}
declare module 'puppeteer/lib/Errors.js' {
  declare module.exports: $Exports<'puppeteer/lib/Errors'>;
}
declare module 'puppeteer/lib/Events.js' {
  declare module.exports: $Exports<'puppeteer/lib/Events'>;
}
declare module 'puppeteer/lib/ExecutionContext.js' {
  declare module.exports: $Exports<'puppeteer/lib/ExecutionContext'>;
}
declare module 'puppeteer/lib/FileChooser.js' {
  declare module.exports: $Exports<'puppeteer/lib/FileChooser'>;
}
declare module 'puppeteer/lib/FrameManager.js' {
  declare module.exports: $Exports<'puppeteer/lib/FrameManager'>;
}
declare module 'puppeteer/lib/helper.js' {
  declare module.exports: $Exports<'puppeteer/lib/helper'>;
}
declare module 'puppeteer/lib/HTTPRequest.js' {
  declare module.exports: $Exports<'puppeteer/lib/HTTPRequest'>;
}
declare module 'puppeteer/lib/HTTPResponse.js' {
  declare module.exports: $Exports<'puppeteer/lib/HTTPResponse'>;
}
declare module 'puppeteer/lib/Input.js' {
  declare module.exports: $Exports<'puppeteer/lib/Input'>;
}
declare module 'puppeteer/lib/JSHandle.js' {
  declare module.exports: $Exports<'puppeteer/lib/JSHandle'>;
}
declare module 'puppeteer/lib/Launcher.js' {
  declare module.exports: $Exports<'puppeteer/lib/Launcher'>;
}
declare module 'puppeteer/lib/launcher/BrowserRunner.js' {
  declare module.exports: $Exports<'puppeteer/lib/launcher/BrowserRunner'>;
}
declare module 'puppeteer/lib/launcher/LaunchOptions.js' {
  declare module.exports: $Exports<'puppeteer/lib/launcher/LaunchOptions'>;
}
declare module 'puppeteer/lib/LifecycleWatcher.js' {
  declare module.exports: $Exports<'puppeteer/lib/LifecycleWatcher'>;
}
declare module 'puppeteer/lib/NetworkManager.js' {
  declare module.exports: $Exports<'puppeteer/lib/NetworkManager'>;
}
declare module 'puppeteer/lib/Page.js' {
  declare module.exports: $Exports<'puppeteer/lib/Page'>;
}
declare module 'puppeteer/lib/PipeTransport.js' {
  declare module.exports: $Exports<'puppeteer/lib/PipeTransport'>;
}
declare module 'puppeteer/lib/Puppeteer.js' {
  declare module.exports: $Exports<'puppeteer/lib/Puppeteer'>;
}
declare module 'puppeteer/lib/PuppeteerViewport.js' {
  declare module.exports: $Exports<'puppeteer/lib/PuppeteerViewport'>;
}
declare module 'puppeteer/lib/QueryHandler.js' {
  declare module.exports: $Exports<'puppeteer/lib/QueryHandler'>;
}
declare module 'puppeteer/lib/SecurityDetails.js' {
  declare module.exports: $Exports<'puppeteer/lib/SecurityDetails'>;
}
declare module 'puppeteer/lib/Target.js' {
  declare module.exports: $Exports<'puppeteer/lib/Target'>;
}
declare module 'puppeteer/lib/TimeoutSettings.js' {
  declare module.exports: $Exports<'puppeteer/lib/TimeoutSettings'>;
}
declare module 'puppeteer/lib/Tracing.js' {
  declare module.exports: $Exports<'puppeteer/lib/Tracing'>;
}
declare module 'puppeteer/lib/USKeyboardLayout.js' {
  declare module.exports: $Exports<'puppeteer/lib/USKeyboardLayout'>;
}
declare module 'puppeteer/lib/WebSocketTransport.js' {
  declare module.exports: $Exports<'puppeteer/lib/WebSocketTransport'>;
}
declare module 'puppeteer/lib/WebWorker.js' {
  declare module.exports: $Exports<'puppeteer/lib/WebWorker'>;
}
declare module 'puppeteer/typescript-if-required.js' {
  declare module.exports: $Exports<'puppeteer/typescript-if-required'>;
}
