// flow-typed signature: d1890be1385d8cd510aec5903f6f2411
// flow-typed version: <<STUB>>/react-aria-live_v2.0.5/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-aria-live'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-aria-live' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-aria-live/es' {
  declare module.exports: any;
}

declare module 'react-aria-live/es/modules/Announcer' {
  declare module.exports: any;
}

declare module 'react-aria-live/es/modules/AnnouncerContext' {
  declare module.exports: any;
}

declare module 'react-aria-live/es/modules/AnnouncerMessage' {
  declare module.exports: any;
}

declare module 'react-aria-live/es/modules/LiveAnnouncer' {
  declare module.exports: any;
}

declare module 'react-aria-live/es/modules/LiveMessage' {
  declare module.exports: any;
}

declare module 'react-aria-live/es/modules/LiveMessenger' {
  declare module.exports: any;
}

declare module 'react-aria-live/es/modules/MessageBlock' {
  declare module.exports: any;
}

declare module 'react-aria-live/es/setupTests' {
  declare module.exports: any;
}

declare module 'react-aria-live/lib' {
  declare module.exports: any;
}

declare module 'react-aria-live/lib/modules/Announcer' {
  declare module.exports: any;
}

declare module 'react-aria-live/lib/modules/AnnouncerContext' {
  declare module.exports: any;
}

declare module 'react-aria-live/lib/modules/AnnouncerMessage' {
  declare module.exports: any;
}

declare module 'react-aria-live/lib/modules/LiveAnnouncer' {
  declare module.exports: any;
}

declare module 'react-aria-live/lib/modules/LiveMessage' {
  declare module.exports: any;
}

declare module 'react-aria-live/lib/modules/LiveMessenger' {
  declare module.exports: any;
}

declare module 'react-aria-live/lib/modules/MessageBlock' {
  declare module.exports: any;
}

declare module 'react-aria-live/lib/setupTests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-aria-live/es/index' {
  declare module.exports: $Exports<'react-aria-live/es'>;
}
declare module 'react-aria-live/es/index.js' {
  declare module.exports: $Exports<'react-aria-live/es'>;
}
declare module 'react-aria-live/es/modules/Announcer.js' {
  declare module.exports: $Exports<'react-aria-live/es/modules/Announcer'>;
}
declare module 'react-aria-live/es/modules/AnnouncerContext.js' {
  declare module.exports: $Exports<'react-aria-live/es/modules/AnnouncerContext'>;
}
declare module 'react-aria-live/es/modules/AnnouncerMessage.js' {
  declare module.exports: $Exports<'react-aria-live/es/modules/AnnouncerMessage'>;
}
declare module 'react-aria-live/es/modules/LiveAnnouncer.js' {
  declare module.exports: $Exports<'react-aria-live/es/modules/LiveAnnouncer'>;
}
declare module 'react-aria-live/es/modules/LiveMessage.js' {
  declare module.exports: $Exports<'react-aria-live/es/modules/LiveMessage'>;
}
declare module 'react-aria-live/es/modules/LiveMessenger.js' {
  declare module.exports: $Exports<'react-aria-live/es/modules/LiveMessenger'>;
}
declare module 'react-aria-live/es/modules/MessageBlock.js' {
  declare module.exports: $Exports<'react-aria-live/es/modules/MessageBlock'>;
}
declare module 'react-aria-live/es/setupTests.js' {
  declare module.exports: $Exports<'react-aria-live/es/setupTests'>;
}
declare module 'react-aria-live/lib/index' {
  declare module.exports: $Exports<'react-aria-live/lib'>;
}
declare module 'react-aria-live/lib/index.js' {
  declare module.exports: $Exports<'react-aria-live/lib'>;
}
declare module 'react-aria-live/lib/modules/Announcer.js' {
  declare module.exports: $Exports<'react-aria-live/lib/modules/Announcer'>;
}
declare module 'react-aria-live/lib/modules/AnnouncerContext.js' {
  declare module.exports: $Exports<'react-aria-live/lib/modules/AnnouncerContext'>;
}
declare module 'react-aria-live/lib/modules/AnnouncerMessage.js' {
  declare module.exports: $Exports<'react-aria-live/lib/modules/AnnouncerMessage'>;
}
declare module 'react-aria-live/lib/modules/LiveAnnouncer.js' {
  declare module.exports: $Exports<'react-aria-live/lib/modules/LiveAnnouncer'>;
}
declare module 'react-aria-live/lib/modules/LiveMessage.js' {
  declare module.exports: $Exports<'react-aria-live/lib/modules/LiveMessage'>;
}
declare module 'react-aria-live/lib/modules/LiveMessenger.js' {
  declare module.exports: $Exports<'react-aria-live/lib/modules/LiveMessenger'>;
}
declare module 'react-aria-live/lib/modules/MessageBlock.js' {
  declare module.exports: $Exports<'react-aria-live/lib/modules/MessageBlock'>;
}
declare module 'react-aria-live/lib/setupTests.js' {
  declare module.exports: $Exports<'react-aria-live/lib/setupTests'>;
}
