// flow-typed signature: 5ce4a692f81abe651bf04fca05149835
// flow-typed version: <<STUB>>/react-aria-menubutton_v6.2.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-aria-menubutton'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-aria-menubutton' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-aria-menubutton/dist/Button' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/dist/createManager' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/dist/externalStateControl' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/dist' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/dist/Menu' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/dist/MenuItem' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/dist/specialAssign' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/dist/Wrapper' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/__tests__/Button.test' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/__tests__/createManager.test' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/__tests__/helpers/createMockKeyEvent' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/__tests__/helpers/createMockManager' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/__tests__/helpers/jest-setup' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/__tests__/helpers/MockWrapper' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/__tests__/helpers/raf' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/__tests__/Menu.test' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/__tests__/MenuItem.test' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/Button' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/createManager' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/externalStateControl' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/Menu' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/MenuItem' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/specialAssign' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/src/Wrapper' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/umd/ReactAriaMenuButton' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/webpack-demo.config' {
  declare module.exports: any;
}

declare module 'react-aria-menubutton/webpack-umd.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-aria-menubutton/dist/Button.js' {
  declare module.exports: $Exports<'react-aria-menubutton/dist/Button'>;
}
declare module 'react-aria-menubutton/dist/createManager.js' {
  declare module.exports: $Exports<'react-aria-menubutton/dist/createManager'>;
}
declare module 'react-aria-menubutton/dist/externalStateControl.js' {
  declare module.exports: $Exports<'react-aria-menubutton/dist/externalStateControl'>;
}
declare module 'react-aria-menubutton/dist/index' {
  declare module.exports: $Exports<'react-aria-menubutton/dist'>;
}
declare module 'react-aria-menubutton/dist/index.js' {
  declare module.exports: $Exports<'react-aria-menubutton/dist'>;
}
declare module 'react-aria-menubutton/dist/Menu.js' {
  declare module.exports: $Exports<'react-aria-menubutton/dist/Menu'>;
}
declare module 'react-aria-menubutton/dist/MenuItem.js' {
  declare module.exports: $Exports<'react-aria-menubutton/dist/MenuItem'>;
}
declare module 'react-aria-menubutton/dist/specialAssign.js' {
  declare module.exports: $Exports<'react-aria-menubutton/dist/specialAssign'>;
}
declare module 'react-aria-menubutton/dist/Wrapper.js' {
  declare module.exports: $Exports<'react-aria-menubutton/dist/Wrapper'>;
}
declare module 'react-aria-menubutton/src/__tests__/Button.test.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/__tests__/Button.test'>;
}
declare module 'react-aria-menubutton/src/__tests__/createManager.test.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/__tests__/createManager.test'>;
}
declare module 'react-aria-menubutton/src/__tests__/helpers/createMockKeyEvent.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/__tests__/helpers/createMockKeyEvent'>;
}
declare module 'react-aria-menubutton/src/__tests__/helpers/createMockManager.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/__tests__/helpers/createMockManager'>;
}
declare module 'react-aria-menubutton/src/__tests__/helpers/jest-setup.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/__tests__/helpers/jest-setup'>;
}
declare module 'react-aria-menubutton/src/__tests__/helpers/MockWrapper.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/__tests__/helpers/MockWrapper'>;
}
declare module 'react-aria-menubutton/src/__tests__/helpers/raf.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/__tests__/helpers/raf'>;
}
declare module 'react-aria-menubutton/src/__tests__/Menu.test.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/__tests__/Menu.test'>;
}
declare module 'react-aria-menubutton/src/__tests__/MenuItem.test.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/__tests__/MenuItem.test'>;
}
declare module 'react-aria-menubutton/src/Button.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/Button'>;
}
declare module 'react-aria-menubutton/src/createManager.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/createManager'>;
}
declare module 'react-aria-menubutton/src/externalStateControl.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/externalStateControl'>;
}
declare module 'react-aria-menubutton/src/index' {
  declare module.exports: $Exports<'react-aria-menubutton/src'>;
}
declare module 'react-aria-menubutton/src/index.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src'>;
}
declare module 'react-aria-menubutton/src/Menu.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/Menu'>;
}
declare module 'react-aria-menubutton/src/MenuItem.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/MenuItem'>;
}
declare module 'react-aria-menubutton/src/specialAssign.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/specialAssign'>;
}
declare module 'react-aria-menubutton/src/Wrapper.js' {
  declare module.exports: $Exports<'react-aria-menubutton/src/Wrapper'>;
}
declare module 'react-aria-menubutton/umd/ReactAriaMenuButton.js' {
  declare module.exports: $Exports<'react-aria-menubutton/umd/ReactAriaMenuButton'>;
}
declare module 'react-aria-menubutton/webpack-demo.config.js' {
  declare module.exports: $Exports<'react-aria-menubutton/webpack-demo.config'>;
}
declare module 'react-aria-menubutton/webpack-umd.config.js' {
  declare module.exports: $Exports<'react-aria-menubutton/webpack-umd.config'>;
}
