// flow-typed signature: 118428386db4c0d0fd3409c77352b56f
// flow-typed version: <<STUB>>/resemblejs_v^3.2.4/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resemblejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'resemblejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'resemblejs/compareImages' {
  declare module.exports: any;
}

declare module 'resemblejs/resemble' {
  declare module.exports: any;
}

// Filename aliases
declare module 'resemblejs/compareImages.js' {
  declare module.exports: $Exports<'resemblejs/compareImages'>;
}
declare module 'resemblejs/resemble.js' {
  declare module.exports: $Exports<'resemblejs/resemble'>;
}
