// flow-typed signature: 0613176036f299a3f26a86b255912171
// flow-typed version: <<STUB>>/rgbquant_vgit+https://github.com/leeoniya/RgbQuant.js.git/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rgbquant'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rgbquant' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rgbquant/demo/js/demo' {
  declare module.exports: any;
}

declare module 'rgbquant/demo/js/helpers' {
  declare module.exports: any;
}

declare module 'rgbquant/demo/js/jquery-2.0.3.min' {
  declare module.exports: any;
}

declare module 'rgbquant/demo/js/preCode' {
  declare module.exports: any;
}

declare module 'rgbquant/demo/js/timer' {
  declare module.exports: any;
}

declare module 'rgbquant/src/rgbquant' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rgbquant/demo/js/demo.js' {
  declare module.exports: $Exports<'rgbquant/demo/js/demo'>;
}
declare module 'rgbquant/demo/js/helpers.js' {
  declare module.exports: $Exports<'rgbquant/demo/js/helpers'>;
}
declare module 'rgbquant/demo/js/jquery-2.0.3.min.js' {
  declare module.exports: $Exports<'rgbquant/demo/js/jquery-2.0.3.min'>;
}
declare module 'rgbquant/demo/js/preCode.js' {
  declare module.exports: $Exports<'rgbquant/demo/js/preCode'>;
}
declare module 'rgbquant/demo/js/timer.js' {
  declare module.exports: $Exports<'rgbquant/demo/js/timer'>;
}
declare module 'rgbquant/src/rgbquant.js' {
  declare module.exports: $Exports<'rgbquant/src/rgbquant'>;
}
