// flow-typed signature: 4c87c94aa5fe31f560014e2b735c4bd1
// flow-typed version: <<STUB>>/rgbquant_v1.1.2/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rgbquant'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rgbquant' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rgbquant/demo/anim/rgbquant' {
  declare module.exports: any
}

declare module 'rgbquant/demo/js/demo_2' {
  declare module.exports: any
}

declare module 'rgbquant/demo/js/demo' {
  declare module.exports: any
}

declare module 'rgbquant/demo/js/helpers' {
  declare module.exports: any
}

declare module 'rgbquant/demo/js/jquery-2.0.3.min' {
  declare module.exports: any
}

declare module 'rgbquant/demo/js/preCode' {
  declare module.exports: any
}

declare module 'rgbquant/demo/js/timer' {
  declare module.exports: any
}

declare module 'rgbquant/src/convert' {
  declare module.exports: any
}

declare module 'rgbquant/src/diff' {
  declare module.exports: any
}

declare module 'rgbquant/src/rgbquant_2' {
  declare module.exports: any
}

declare module 'rgbquant/src/rgbquant_3' {
  declare module.exports: any
}

declare module 'rgbquant/src/rgbquant_4' {
  declare module.exports: any
}

declare module 'rgbquant/src/rgbquant' {
  declare module.exports: any
}

// Filename aliases
declare module 'rgbquant/demo/anim/rgbquant.js' {
  declare module.exports: $Exports<'rgbquant/demo/anim/rgbquant'>
}
declare module 'rgbquant/demo/js/demo_2.js' {
  declare module.exports: $Exports<'rgbquant/demo/js/demo_2'>
}
declare module 'rgbquant/demo/js/demo.js' {
  declare module.exports: $Exports<'rgbquant/demo/js/demo'>
}
declare module 'rgbquant/demo/js/helpers.js' {
  declare module.exports: $Exports<'rgbquant/demo/js/helpers'>
}
declare module 'rgbquant/demo/js/jquery-2.0.3.min.js' {
  declare module.exports: $Exports<'rgbquant/demo/js/jquery-2.0.3.min'>
}
declare module 'rgbquant/demo/js/preCode.js' {
  declare module.exports: $Exports<'rgbquant/demo/js/preCode'>
}
declare module 'rgbquant/demo/js/timer.js' {
  declare module.exports: $Exports<'rgbquant/demo/js/timer'>
}
declare module 'rgbquant/src/convert.js' {
  declare module.exports: $Exports<'rgbquant/src/convert'>
}
declare module 'rgbquant/src/diff.js' {
  declare module.exports: $Exports<'rgbquant/src/diff'>
}
declare module 'rgbquant/src/rgbquant_2.js' {
  declare module.exports: $Exports<'rgbquant/src/rgbquant_2'>
}
declare module 'rgbquant/src/rgbquant_3.js' {
  declare module.exports: $Exports<'rgbquant/src/rgbquant_3'>
}
declare module 'rgbquant/src/rgbquant_4.js' {
  declare module.exports: $Exports<'rgbquant/src/rgbquant_4'>
}
declare module 'rgbquant/src/rgbquant.js' {
  declare module.exports: $Exports<'rgbquant/src/rgbquant'>
}
