// flow-typed signature: e335faf2320cf9f8bac038115e4158e5
// flow-typed version: <<STUB>>/sass-math-pow_v0.1.5/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-math-pow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-math-pow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sass-math-pow/eyeglass-exports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sass-math-pow/eyeglass-exports.js' {
  declare module.exports: $Exports<'sass-math-pow/eyeglass-exports'>;
}
