// flow-typed signature: 14b068ce81c145b210fc32492dc8916d
// flow-typed version: <<STUB>>/sass-math-pow_v0.2.0/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-math-pow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-math-pow' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sass-math-pow/eyeglass-exports' {
  declare module.exports: any
}

// Filename aliases
declare module 'sass-math-pow/eyeglass-exports.js' {
  declare module.exports: $Exports<'sass-math-pow/eyeglass-exports'>
}
