// flow-typed signature: 3d9cdf70bcec7320e69581519f897aaa
// flow-typed version: <<STUB>>/sassyjson_v1.1.8/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sassyjson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sassyjson' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sassyjson/Gruntfile' {
  declare module.exports: any
}

// Filename aliases
declare module 'sassyjson/Gruntfile.js' {
  declare module.exports: $Exports<'sassyjson/Gruntfile'>
}
