// flow-typed signature: a92f0ffca8d853843be70e65f524b3e1
// flow-typed version: <<STUB>>/scroll_v3.0.1/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scroll/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scroll/index' {
  declare module.exports: $Exports<'scroll'>;
}
declare module 'scroll/index.js' {
  declare module.exports: $Exports<'scroll'>;
}
declare module 'scroll/test.js' {
  declare module.exports: $Exports<'scroll/test'>;
}
