// flow-typed signature: fa3478f81a2d2651c4b64f3d15266333
// flow-typed version: <<STUB>>/tailwindcss_v3.1.6/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tailwindcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tailwindcss' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tailwindcss/colors' {
  declare module.exports: any
}

declare module 'tailwindcss/defaultConfig' {
  declare module.exports: any
}

declare module 'tailwindcss/defaultTheme' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/cli-peer-dependencies' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/cli' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/constants' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/corePluginList' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/corePlugins' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/featureFlags' {
  declare module.exports: any
}

declare module 'tailwindcss/lib' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/cacheInvalidation' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/collapseAdjacentRules' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/collapseDuplicateDeclarations' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/defaultExtractor' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/detectNesting' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/evaluateTailwindFunctions' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/expandApplyAtRules' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/expandTailwindAtRules' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/generateRules' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/getModuleDependencies' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/normalizeTailwindDirectives' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/partitionApplyAtRules' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/regex' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/resolveDefaultsAtRules' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/setupContextUtils' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/setupTrackingContext' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/sharedState' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/lib/substituteScreenAtRules' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/postcss-plugins/nesting' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/postcss-plugins/nesting/plugin' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/processTailwindFeatures' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/public/colors' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/public/create-plugin' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/public/default-config' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/public/default-theme' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/public/resolve-config' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/bigSign' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/buildMediaQuery' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/cloneDeep' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/cloneNodes' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/color' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/configurePlugins' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/createPlugin' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/createUtilityPlugin' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/dataTypes' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/defaults' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/escapeClassName' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/escapeCommas' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/flattenColorPalette' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/formatVariantSelector' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/getAllConfigs' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/hashConfig' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/isKeyframeRule' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/isPlainObject' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/isValidArbitraryValue' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/log' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/nameClass' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/negateValue' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/normalizeConfig' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/normalizeScreens' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/parseAnimationValue' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/parseBoxShadowValue' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/parseDependency' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/parseObjectStyles' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/pluginUtils' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/prefixSelector' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/removeAlphaVariables' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/resolveConfig' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/resolveConfigPath' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/responsive' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/splitAtTopLevelOnly' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/tap' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/toColorValue' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/toPath' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/transformThemeValue' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/validateConfig' {
  declare module.exports: any
}

declare module 'tailwindcss/lib/util/withAlphaVariable' {
  declare module.exports: any
}

declare module 'tailwindcss/nesting' {
  declare module.exports: any
}

declare module 'tailwindcss/peers' {
  declare module.exports: any
}

declare module 'tailwindcss/plugin' {
  declare module.exports: any
}

declare module 'tailwindcss/prettier.config' {
  declare module.exports: any
}

declare module 'tailwindcss/resolveConfig' {
  declare module.exports: any
}

declare module 'tailwindcss/scripts/create-plugin-list' {
  declare module.exports: any
}

declare module 'tailwindcss/scripts/generate-types' {
  declare module.exports: any
}

declare module 'tailwindcss/scripts/install-integrations' {
  declare module.exports: any
}

declare module 'tailwindcss/scripts/rebuildFixtures' {
  declare module.exports: any
}

declare module 'tailwindcss/scripts/type-utils' {
  declare module.exports: any
}

declare module 'tailwindcss/src/cli-peer-dependencies' {
  declare module.exports: any
}

declare module 'tailwindcss/src/cli' {
  declare module.exports: any
}

declare module 'tailwindcss/src/constants' {
  declare module.exports: any
}

declare module 'tailwindcss/src/corePluginList' {
  declare module.exports: any
}

declare module 'tailwindcss/src/corePlugins' {
  declare module.exports: any
}

declare module 'tailwindcss/src/featureFlags' {
  declare module.exports: any
}

declare module 'tailwindcss/src' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/cacheInvalidation' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/collapseAdjacentRules' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/collapseDuplicateDeclarations' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/defaultExtractor' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/detectNesting' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/evaluateTailwindFunctions' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/expandApplyAtRules' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/expandTailwindAtRules' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/generateRules' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/getModuleDependencies' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/normalizeTailwindDirectives' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/partitionApplyAtRules' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/regex' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/resolveDefaultsAtRules' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/setupContextUtils' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/setupTrackingContext' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/sharedState' {
  declare module.exports: any
}

declare module 'tailwindcss/src/lib/substituteScreenAtRules' {
  declare module.exports: any
}

declare module 'tailwindcss/src/postcss-plugins/nesting' {
  declare module.exports: any
}

declare module 'tailwindcss/src/postcss-plugins/nesting/plugin' {
  declare module.exports: any
}

declare module 'tailwindcss/src/processTailwindFeatures' {
  declare module.exports: any
}

declare module 'tailwindcss/src/public/colors' {
  declare module.exports: any
}

declare module 'tailwindcss/src/public/create-plugin' {
  declare module.exports: any
}

declare module 'tailwindcss/src/public/default-config' {
  declare module.exports: any
}

declare module 'tailwindcss/src/public/default-theme' {
  declare module.exports: any
}

declare module 'tailwindcss/src/public/resolve-config' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/bigSign' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/buildMediaQuery' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/cloneDeep' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/cloneNodes' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/color' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/configurePlugins' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/createPlugin' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/createUtilityPlugin' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/dataTypes' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/defaults' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/escapeClassName' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/escapeCommas' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/flattenColorPalette' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/formatVariantSelector' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/getAllConfigs' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/hashConfig' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/isKeyframeRule' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/isPlainObject' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/isValidArbitraryValue' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/log' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/nameClass' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/negateValue' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/normalizeConfig' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/normalizeScreens' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/parseAnimationValue' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/parseBoxShadowValue' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/parseDependency' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/parseObjectStyles' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/pluginUtils' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/prefixSelector' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/removeAlphaVariables' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/resolveConfig' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/resolveConfigPath' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/responsive' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/splitAtTopLevelOnly' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/tap' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/toColorValue' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/toPath' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/transformThemeValue' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/validateConfig' {
  declare module.exports: any
}

declare module 'tailwindcss/src/util/withAlphaVariable' {
  declare module.exports: any
}

declare module 'tailwindcss/stubs/defaultConfig.stub' {
  declare module.exports: any
}

declare module 'tailwindcss/stubs/defaultPostCssConfig.stub' {
  declare module.exports: any
}

declare module 'tailwindcss/stubs/simpleConfig.stub' {
  declare module.exports: any
}

// Filename aliases
declare module 'tailwindcss/colors.js' {
  declare module.exports: $Exports<'tailwindcss/colors'>
}
declare module 'tailwindcss/defaultConfig.js' {
  declare module.exports: $Exports<'tailwindcss/defaultConfig'>
}
declare module 'tailwindcss/defaultTheme.js' {
  declare module.exports: $Exports<'tailwindcss/defaultTheme'>
}
declare module 'tailwindcss/lib/cli-peer-dependencies.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli-peer-dependencies'>
}
declare module 'tailwindcss/lib/cli.js' {
  declare module.exports: $Exports<'tailwindcss/lib/cli'>
}
declare module 'tailwindcss/lib/constants.js' {
  declare module.exports: $Exports<'tailwindcss/lib/constants'>
}
declare module 'tailwindcss/lib/corePluginList.js' {
  declare module.exports: $Exports<'tailwindcss/lib/corePluginList'>
}
declare module 'tailwindcss/lib/corePlugins.js' {
  declare module.exports: $Exports<'tailwindcss/lib/corePlugins'>
}
declare module 'tailwindcss/lib/featureFlags.js' {
  declare module.exports: $Exports<'tailwindcss/lib/featureFlags'>
}
declare module 'tailwindcss/lib/index' {
  declare module.exports: $Exports<'tailwindcss/lib'>
}
declare module 'tailwindcss/lib/index.js' {
  declare module.exports: $Exports<'tailwindcss/lib'>
}
declare module 'tailwindcss/lib/lib/cacheInvalidation.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/cacheInvalidation'>
}
declare module 'tailwindcss/lib/lib/collapseAdjacentRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/collapseAdjacentRules'>
}
declare module 'tailwindcss/lib/lib/collapseDuplicateDeclarations.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/collapseDuplicateDeclarations'>
}
declare module 'tailwindcss/lib/lib/defaultExtractor.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/defaultExtractor'>
}
declare module 'tailwindcss/lib/lib/detectNesting.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/detectNesting'>
}
declare module 'tailwindcss/lib/lib/evaluateTailwindFunctions.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/evaluateTailwindFunctions'>
}
declare module 'tailwindcss/lib/lib/expandApplyAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/expandApplyAtRules'>
}
declare module 'tailwindcss/lib/lib/expandTailwindAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/expandTailwindAtRules'>
}
declare module 'tailwindcss/lib/lib/generateRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/generateRules'>
}
declare module 'tailwindcss/lib/lib/getModuleDependencies.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/getModuleDependencies'>
}
declare module 'tailwindcss/lib/lib/normalizeTailwindDirectives.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/normalizeTailwindDirectives'>
}
declare module 'tailwindcss/lib/lib/partitionApplyAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/partitionApplyAtRules'>
}
declare module 'tailwindcss/lib/lib/regex.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/regex'>
}
declare module 'tailwindcss/lib/lib/resolveDefaultsAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/resolveDefaultsAtRules'>
}
declare module 'tailwindcss/lib/lib/setupContextUtils.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/setupContextUtils'>
}
declare module 'tailwindcss/lib/lib/setupTrackingContext.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/setupTrackingContext'>
}
declare module 'tailwindcss/lib/lib/sharedState.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/sharedState'>
}
declare module 'tailwindcss/lib/lib/substituteScreenAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/lib/lib/substituteScreenAtRules'>
}
declare module 'tailwindcss/lib/postcss-plugins/nesting/index' {
  declare module.exports: $Exports<'tailwindcss/lib/postcss-plugins/nesting'>
}
declare module 'tailwindcss/lib/postcss-plugins/nesting/index.js' {
  declare module.exports: $Exports<'tailwindcss/lib/postcss-plugins/nesting'>
}
declare module 'tailwindcss/lib/postcss-plugins/nesting/plugin.js' {
  declare module.exports: $Exports<'tailwindcss/lib/postcss-plugins/nesting/plugin'>
}
declare module 'tailwindcss/lib/processTailwindFeatures.js' {
  declare module.exports: $Exports<'tailwindcss/lib/processTailwindFeatures'>
}
declare module 'tailwindcss/lib/public/colors.js' {
  declare module.exports: $Exports<'tailwindcss/lib/public/colors'>
}
declare module 'tailwindcss/lib/public/create-plugin.js' {
  declare module.exports: $Exports<'tailwindcss/lib/public/create-plugin'>
}
declare module 'tailwindcss/lib/public/default-config.js' {
  declare module.exports: $Exports<'tailwindcss/lib/public/default-config'>
}
declare module 'tailwindcss/lib/public/default-theme.js' {
  declare module.exports: $Exports<'tailwindcss/lib/public/default-theme'>
}
declare module 'tailwindcss/lib/public/resolve-config.js' {
  declare module.exports: $Exports<'tailwindcss/lib/public/resolve-config'>
}
declare module 'tailwindcss/lib/util/bigSign.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/bigSign'>
}
declare module 'tailwindcss/lib/util/buildMediaQuery.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/buildMediaQuery'>
}
declare module 'tailwindcss/lib/util/cloneDeep.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/cloneDeep'>
}
declare module 'tailwindcss/lib/util/cloneNodes.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/cloneNodes'>
}
declare module 'tailwindcss/lib/util/color.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/color'>
}
declare module 'tailwindcss/lib/util/configurePlugins.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/configurePlugins'>
}
declare module 'tailwindcss/lib/util/createPlugin.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/createPlugin'>
}
declare module 'tailwindcss/lib/util/createUtilityPlugin.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/createUtilityPlugin'>
}
declare module 'tailwindcss/lib/util/dataTypes.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/dataTypes'>
}
declare module 'tailwindcss/lib/util/defaults.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/defaults'>
}
declare module 'tailwindcss/lib/util/escapeClassName.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/escapeClassName'>
}
declare module 'tailwindcss/lib/util/escapeCommas.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/escapeCommas'>
}
declare module 'tailwindcss/lib/util/flattenColorPalette.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/flattenColorPalette'>
}
declare module 'tailwindcss/lib/util/formatVariantSelector.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/formatVariantSelector'>
}
declare module 'tailwindcss/lib/util/getAllConfigs.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/getAllConfigs'>
}
declare module 'tailwindcss/lib/util/hashConfig.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/hashConfig'>
}
declare module 'tailwindcss/lib/util/isKeyframeRule.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/isKeyframeRule'>
}
declare module 'tailwindcss/lib/util/isPlainObject.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/isPlainObject'>
}
declare module 'tailwindcss/lib/util/isValidArbitraryValue.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/isValidArbitraryValue'>
}
declare module 'tailwindcss/lib/util/log.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/log'>
}
declare module 'tailwindcss/lib/util/nameClass.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/nameClass'>
}
declare module 'tailwindcss/lib/util/negateValue.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/negateValue'>
}
declare module 'tailwindcss/lib/util/normalizeConfig.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/normalizeConfig'>
}
declare module 'tailwindcss/lib/util/normalizeScreens.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/normalizeScreens'>
}
declare module 'tailwindcss/lib/util/parseAnimationValue.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/parseAnimationValue'>
}
declare module 'tailwindcss/lib/util/parseBoxShadowValue.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/parseBoxShadowValue'>
}
declare module 'tailwindcss/lib/util/parseDependency.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/parseDependency'>
}
declare module 'tailwindcss/lib/util/parseObjectStyles.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/parseObjectStyles'>
}
declare module 'tailwindcss/lib/util/pluginUtils.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/pluginUtils'>
}
declare module 'tailwindcss/lib/util/prefixSelector.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/prefixSelector'>
}
declare module 'tailwindcss/lib/util/removeAlphaVariables.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/removeAlphaVariables'>
}
declare module 'tailwindcss/lib/util/resolveConfig.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/resolveConfig'>
}
declare module 'tailwindcss/lib/util/resolveConfigPath.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/resolveConfigPath'>
}
declare module 'tailwindcss/lib/util/responsive.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/responsive'>
}
declare module 'tailwindcss/lib/util/splitAtTopLevelOnly.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/splitAtTopLevelOnly'>
}
declare module 'tailwindcss/lib/util/tap.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/tap'>
}
declare module 'tailwindcss/lib/util/toColorValue.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/toColorValue'>
}
declare module 'tailwindcss/lib/util/toPath.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/toPath'>
}
declare module 'tailwindcss/lib/util/transformThemeValue.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/transformThemeValue'>
}
declare module 'tailwindcss/lib/util/validateConfig.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/validateConfig'>
}
declare module 'tailwindcss/lib/util/withAlphaVariable.js' {
  declare module.exports: $Exports<'tailwindcss/lib/util/withAlphaVariable'>
}
declare module 'tailwindcss/nesting/index' {
  declare module.exports: $Exports<'tailwindcss/nesting'>
}
declare module 'tailwindcss/nesting/index.js' {
  declare module.exports: $Exports<'tailwindcss/nesting'>
}
declare module 'tailwindcss/peers/index' {
  declare module.exports: $Exports<'tailwindcss/peers'>
}
declare module 'tailwindcss/peers/index.js' {
  declare module.exports: $Exports<'tailwindcss/peers'>
}
declare module 'tailwindcss/plugin.js' {
  declare module.exports: $Exports<'tailwindcss/plugin'>
}
declare module 'tailwindcss/prettier.config.js' {
  declare module.exports: $Exports<'tailwindcss/prettier.config'>
}
declare module 'tailwindcss/resolveConfig.js' {
  declare module.exports: $Exports<'tailwindcss/resolveConfig'>
}
declare module 'tailwindcss/scripts/create-plugin-list.js' {
  declare module.exports: $Exports<'tailwindcss/scripts/create-plugin-list'>
}
declare module 'tailwindcss/scripts/generate-types.js' {
  declare module.exports: $Exports<'tailwindcss/scripts/generate-types'>
}
declare module 'tailwindcss/scripts/install-integrations.js' {
  declare module.exports: $Exports<'tailwindcss/scripts/install-integrations'>
}
declare module 'tailwindcss/scripts/rebuildFixtures.js' {
  declare module.exports: $Exports<'tailwindcss/scripts/rebuildFixtures'>
}
declare module 'tailwindcss/scripts/type-utils.js' {
  declare module.exports: $Exports<'tailwindcss/scripts/type-utils'>
}
declare module 'tailwindcss/src/cli-peer-dependencies.js' {
  declare module.exports: $Exports<'tailwindcss/src/cli-peer-dependencies'>
}
declare module 'tailwindcss/src/cli.js' {
  declare module.exports: $Exports<'tailwindcss/src/cli'>
}
declare module 'tailwindcss/src/constants.js' {
  declare module.exports: $Exports<'tailwindcss/src/constants'>
}
declare module 'tailwindcss/src/corePluginList.js' {
  declare module.exports: $Exports<'tailwindcss/src/corePluginList'>
}
declare module 'tailwindcss/src/corePlugins.js' {
  declare module.exports: $Exports<'tailwindcss/src/corePlugins'>
}
declare module 'tailwindcss/src/featureFlags.js' {
  declare module.exports: $Exports<'tailwindcss/src/featureFlags'>
}
declare module 'tailwindcss/src/index' {
  declare module.exports: $Exports<'tailwindcss/src'>
}
declare module 'tailwindcss/src/index.js' {
  declare module.exports: $Exports<'tailwindcss/src'>
}
declare module 'tailwindcss/src/lib/cacheInvalidation.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/cacheInvalidation'>
}
declare module 'tailwindcss/src/lib/collapseAdjacentRules.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/collapseAdjacentRules'>
}
declare module 'tailwindcss/src/lib/collapseDuplicateDeclarations.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/collapseDuplicateDeclarations'>
}
declare module 'tailwindcss/src/lib/defaultExtractor.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/defaultExtractor'>
}
declare module 'tailwindcss/src/lib/detectNesting.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/detectNesting'>
}
declare module 'tailwindcss/src/lib/evaluateTailwindFunctions.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/evaluateTailwindFunctions'>
}
declare module 'tailwindcss/src/lib/expandApplyAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/expandApplyAtRules'>
}
declare module 'tailwindcss/src/lib/expandTailwindAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/expandTailwindAtRules'>
}
declare module 'tailwindcss/src/lib/generateRules.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/generateRules'>
}
declare module 'tailwindcss/src/lib/getModuleDependencies.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/getModuleDependencies'>
}
declare module 'tailwindcss/src/lib/normalizeTailwindDirectives.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/normalizeTailwindDirectives'>
}
declare module 'tailwindcss/src/lib/partitionApplyAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/partitionApplyAtRules'>
}
declare module 'tailwindcss/src/lib/regex.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/regex'>
}
declare module 'tailwindcss/src/lib/resolveDefaultsAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/resolveDefaultsAtRules'>
}
declare module 'tailwindcss/src/lib/setupContextUtils.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/setupContextUtils'>
}
declare module 'tailwindcss/src/lib/setupTrackingContext.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/setupTrackingContext'>
}
declare module 'tailwindcss/src/lib/sharedState.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/sharedState'>
}
declare module 'tailwindcss/src/lib/substituteScreenAtRules.js' {
  declare module.exports: $Exports<'tailwindcss/src/lib/substituteScreenAtRules'>
}
declare module 'tailwindcss/src/postcss-plugins/nesting/index' {
  declare module.exports: $Exports<'tailwindcss/src/postcss-plugins/nesting'>
}
declare module 'tailwindcss/src/postcss-plugins/nesting/index.js' {
  declare module.exports: $Exports<'tailwindcss/src/postcss-plugins/nesting'>
}
declare module 'tailwindcss/src/postcss-plugins/nesting/plugin.js' {
  declare module.exports: $Exports<'tailwindcss/src/postcss-plugins/nesting/plugin'>
}
declare module 'tailwindcss/src/processTailwindFeatures.js' {
  declare module.exports: $Exports<'tailwindcss/src/processTailwindFeatures'>
}
declare module 'tailwindcss/src/public/colors.js' {
  declare module.exports: $Exports<'tailwindcss/src/public/colors'>
}
declare module 'tailwindcss/src/public/create-plugin.js' {
  declare module.exports: $Exports<'tailwindcss/src/public/create-plugin'>
}
declare module 'tailwindcss/src/public/default-config.js' {
  declare module.exports: $Exports<'tailwindcss/src/public/default-config'>
}
declare module 'tailwindcss/src/public/default-theme.js' {
  declare module.exports: $Exports<'tailwindcss/src/public/default-theme'>
}
declare module 'tailwindcss/src/public/resolve-config.js' {
  declare module.exports: $Exports<'tailwindcss/src/public/resolve-config'>
}
declare module 'tailwindcss/src/util/bigSign.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/bigSign'>
}
declare module 'tailwindcss/src/util/buildMediaQuery.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/buildMediaQuery'>
}
declare module 'tailwindcss/src/util/cloneDeep.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/cloneDeep'>
}
declare module 'tailwindcss/src/util/cloneNodes.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/cloneNodes'>
}
declare module 'tailwindcss/src/util/color.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/color'>
}
declare module 'tailwindcss/src/util/configurePlugins.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/configurePlugins'>
}
declare module 'tailwindcss/src/util/createPlugin.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/createPlugin'>
}
declare module 'tailwindcss/src/util/createUtilityPlugin.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/createUtilityPlugin'>
}
declare module 'tailwindcss/src/util/dataTypes.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/dataTypes'>
}
declare module 'tailwindcss/src/util/defaults.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/defaults'>
}
declare module 'tailwindcss/src/util/escapeClassName.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/escapeClassName'>
}
declare module 'tailwindcss/src/util/escapeCommas.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/escapeCommas'>
}
declare module 'tailwindcss/src/util/flattenColorPalette.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/flattenColorPalette'>
}
declare module 'tailwindcss/src/util/formatVariantSelector.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/formatVariantSelector'>
}
declare module 'tailwindcss/src/util/getAllConfigs.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/getAllConfigs'>
}
declare module 'tailwindcss/src/util/hashConfig.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/hashConfig'>
}
declare module 'tailwindcss/src/util/isKeyframeRule.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/isKeyframeRule'>
}
declare module 'tailwindcss/src/util/isPlainObject.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/isPlainObject'>
}
declare module 'tailwindcss/src/util/isValidArbitraryValue.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/isValidArbitraryValue'>
}
declare module 'tailwindcss/src/util/log.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/log'>
}
declare module 'tailwindcss/src/util/nameClass.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/nameClass'>
}
declare module 'tailwindcss/src/util/negateValue.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/negateValue'>
}
declare module 'tailwindcss/src/util/normalizeConfig.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/normalizeConfig'>
}
declare module 'tailwindcss/src/util/normalizeScreens.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/normalizeScreens'>
}
declare module 'tailwindcss/src/util/parseAnimationValue.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/parseAnimationValue'>
}
declare module 'tailwindcss/src/util/parseBoxShadowValue.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/parseBoxShadowValue'>
}
declare module 'tailwindcss/src/util/parseDependency.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/parseDependency'>
}
declare module 'tailwindcss/src/util/parseObjectStyles.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/parseObjectStyles'>
}
declare module 'tailwindcss/src/util/pluginUtils.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/pluginUtils'>
}
declare module 'tailwindcss/src/util/prefixSelector.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/prefixSelector'>
}
declare module 'tailwindcss/src/util/removeAlphaVariables.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/removeAlphaVariables'>
}
declare module 'tailwindcss/src/util/resolveConfig.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/resolveConfig'>
}
declare module 'tailwindcss/src/util/resolveConfigPath.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/resolveConfigPath'>
}
declare module 'tailwindcss/src/util/responsive.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/responsive'>
}
declare module 'tailwindcss/src/util/splitAtTopLevelOnly.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/splitAtTopLevelOnly'>
}
declare module 'tailwindcss/src/util/tap.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/tap'>
}
declare module 'tailwindcss/src/util/toColorValue.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/toColorValue'>
}
declare module 'tailwindcss/src/util/toPath.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/toPath'>
}
declare module 'tailwindcss/src/util/transformThemeValue.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/transformThemeValue'>
}
declare module 'tailwindcss/src/util/validateConfig.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/validateConfig'>
}
declare module 'tailwindcss/src/util/withAlphaVariable.js' {
  declare module.exports: $Exports<'tailwindcss/src/util/withAlphaVariable'>
}
declare module 'tailwindcss/stubs/defaultConfig.stub.js' {
  declare module.exports: $Exports<'tailwindcss/stubs/defaultConfig.stub'>
}
declare module 'tailwindcss/stubs/defaultPostCssConfig.stub.js' {
  declare module.exports: $Exports<'tailwindcss/stubs/defaultPostCssConfig.stub'>
}
declare module 'tailwindcss/stubs/simpleConfig.stub.js' {
  declare module.exports: $Exports<'tailwindcss/stubs/simpleConfig.stub'>
}
