// flow-typed signature: 6771601fe4667c1d6ea0bd850e4e0528
// flow-typed version: <<STUB>>/url-search-params-polyfill_v7.0.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-search-params-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-search-params-polyfill' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'url-search-params-polyfill/index' {
  declare module.exports: $Exports<'url-search-params-polyfill'>
}
declare module 'url-search-params-polyfill/index.js' {
  declare module.exports: $Exports<'url-search-params-polyfill'>
}
