// flow-typed signature: 8dd9cc004a16e6c6be5337812741931c
// flow-typed version: <<STUB>>/webpackbar_v4.0.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpackbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpackbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpackbar/dist/webpackbar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpackbar/dist/webpackbar.js' {
  declare module.exports: $Exports<'webpackbar/dist/webpackbar'>;
}
