// flow-typed signature: dbb98b19fb18a6420b1f955beda03e13
// flow-typed version: <<STUB>>/webpack-clean_v1.2.3/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-clean'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-clean' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-clean/test/test' {
  declare module.exports: any;
}

declare module 'webpack-clean/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-clean/index' {
  declare module.exports: $Exports<'webpack-clean'>;
}
declare module 'webpack-clean/index.js' {
  declare module.exports: $Exports<'webpack-clean'>;
}
declare module 'webpack-clean/test/test.js' {
  declare module.exports: $Exports<'webpack-clean/test/test'>;
}
declare module 'webpack-clean/wallaby.js' {
  declare module.exports: $Exports<'webpack-clean/wallaby'>;
}
