// flow-typed signature: df70f088c7a21f541ecdc009ade0bd59
// flow-typed version: <<STUB>>/webpackbar_v5.0.2/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpackbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpackbar' {
  declare module.exports: any
}
