// flow-typed signature: 77c55c9ef3f6122f666674cab241c54b
// flow-typed version: <<STUB>>/worker-loader_v3.0.8/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'worker-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'worker-loader' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'worker-loader/dist/cjs' {
  declare module.exports: any
}

declare module 'worker-loader/dist' {
  declare module.exports: any
}

declare module 'worker-loader/dist/runtime/inline' {
  declare module.exports: any
}

declare module 'worker-loader/dist/supportWebpack4' {
  declare module.exports: any
}

declare module 'worker-loader/dist/supportWebpack5' {
  declare module.exports: any
}

declare module 'worker-loader/dist/utils' {
  declare module.exports: any
}

// Filename aliases
declare module 'worker-loader/dist/cjs.js' {
  declare module.exports: $Exports<'worker-loader/dist/cjs'>
}
declare module 'worker-loader/dist/index' {
  declare module.exports: $Exports<'worker-loader/dist'>
}
declare module 'worker-loader/dist/index.js' {
  declare module.exports: $Exports<'worker-loader/dist'>
}
declare module 'worker-loader/dist/runtime/inline.js' {
  declare module.exports: $Exports<'worker-loader/dist/runtime/inline'>
}
declare module 'worker-loader/dist/supportWebpack4.js' {
  declare module.exports: $Exports<'worker-loader/dist/supportWebpack4'>
}
declare module 'worker-loader/dist/supportWebpack5.js' {
  declare module.exports: $Exports<'worker-loader/dist/supportWebpack5'>
}
declare module 'worker-loader/dist/utils.js' {
  declare module.exports: $Exports<'worker-loader/dist/utils'>
}
