export default {
  'hgsw': {
    'Grays': 'https://sherwin.scene7.com/is/image/sw/HGSW-Grays-MiniMap-400px?fmt=png8&wid=250',
    'Clean & Bright 1/3': 'https://sherwin.scene7.com/is/image/sw/HGSW-CleanBright-left-MiniMap-400px?fmt=png8&wid=250',
    'Clean & Bright 2/3': 'https://sherwin.scene7.com/is/image/sw/HGSW-CleanBright-middle-MiniMap-400px?fmt=png8&wid=250',
    'Clean & Bright 3/3': 'https://sherwin.scene7.com/is/image/sw/HGSW-CleanBright-right-MiniMap-400px?fmt=png8&wid=250',
    'Muted & Shaded 1/3': 'https://sherwin.scene7.com/is/image/sw/HGSW-MutedShaded-left-MiniMap-400px?fmt=png8&wid=250',
    'Muted & Shaded 2/3': 'https://sherwin.scene7.com/is/image/sw/HGSW-MutedShaded-middle-MiniMap-400px?fmt=png8&wid=250',
    'Muted & Shaded 3/3': 'https://sherwin.scene7.com/is/image/sw/HGSW-MutedShaded-right-MiniMap-400px?fmt=png8&wid=250',
    'Whites': 'https://sherwin.scene7.com/is/image/sw/HGSW-Whites-MiniMap-400px?fmt=png8&wid=250',
    'Neutrals': 'https://sherwin.scene7.com/is/image/sw/HGSW-Neutrals-MiniMap-400px?fmt=png8&wid=250'
  },
  'valspar': {
    'Bamboo & Seagrass': 'https://sherwin.scene7.com/is/image/sw/Valspar-BambooSeagrass-MiniMap-400px?fmt=png8&wid=250',
    'Chestnut & Khaki': 'https://sherwin.scene7.com/is/image/sw/Valspar-ChestnutKhaki-MiniMap-400px?fmt=png8&wid=250',
    'Blue & Violet': 'https://sherwin.scene7.com/is/image/sw/Valspar-BlueViolet-MiniMap-400px?fmt=png8&wid=250',
    'Fog & Cocoa': 'https://sherwin.scene7.com/is/image/sw/Valspar-FogCocoa-MiniMap-400px?fmt=png8&wid=250',
    'Gray': 'https://sherwin.scene7.com/is/image/sw/Valspar-Gray-MiniMap-400px?fmt=png8&wid=250',
    'Green & Teal': 'https://sherwin.scene7.com/is/image/sw/Valspar-GreenTeal-MiniMap-400px?fmt=png8&wid=250',
    'Iceberg & Indigo': 'https://sherwin.scene7.com/is/image/sw/Valspar-IcebergIndigo-MiniMap-400px?fmt=png8&wid=250',
    'Moss & Sage': 'https://sherwin.scene7.com/is/image/sw/Valspar-MossSage-MiniMap-400px?fmt=png8&wid=250',
    'Olive & Pine': 'https://sherwin.scene7.com/is/image/sw/Valspar-OlivePine-MiniMap-400px?fmt=png8&wid=250',
    'Neutral': 'https://sherwin.scene7.com/is/image/sw/Valspar-Neutral-MiniMap-400px?fmt=png8&wid=250',
    'Orange & Yellow': 'https://sherwin.scene7.com/is/image/sw/Valspar-OrangeYellow-MiniMap-400px?fmt=png8&wid=250',
    'Peach & Saffron': 'https://sherwin.scene7.com/is/image/sw/Valspar-PeachSaffron-MiniMap-400px?fmt=png8&wid=250',
    'Peacock & Sapphire': 'https://sherwin.scene7.com/is/image/sw/Valspar-PeacockSapphire-MiniMap-400px?fmt=png8&wid=250',
    'Plum & Paprika': 'https://sherwin.scene7.com/is/image/sw/Valspar-PlumPaprika-MiniMap-400px?fmt=png8&wid=250',
    'Sand & Bronze': 'https://sherwin.scene7.com/is/image/sw/Valspar-SandBronze-MiniMap-400px?fmt=png8&wid=250',
    'Red & Pink': 'https://sherwin.scene7.com/is/image/sw/Valspar-RedPink-MiniMap-400px?fmt=png8&wid=250',
    'Slate & Midnight': 'https://sherwin.scene7.com/is/image/sw/Valspar-SlateMidnight-MiniMap-400px?fmt=png8&wid=250',
    'White': 'https://sherwin.scene7.com/is/image/sw/Valspar-White-MiniMap-400px?fmt=png8&wid=250',
    'Wine & Coral': 'https://sherwin.scene7.com/is/image/sw/Valspar-WineCoral-MiniMap-400px?fmt=png8&wid=250'
  },
  'valsparLeftHand': {
    'Bamboo & Seagrass': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-BambooSeagrass-MiniMap-400px?fmt=png8&wid=250',
    'Chestnut & Khaki': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-ChestnutKhaki-MiniMap-400px?fmt=png8&wid=250',
    'Blue & Violet': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-BlueViolet-MiniMap-400px?fmt=png8&wid=250',
    'Fog & Cocoa': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-FogCocoa-MiniMap-400px?fmt=png8&wid=250',
    'Gray': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-Gray-MiniMap-400px?fmt=png8&wid=250',
    'Green & Teal': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-GreenTeal-MiniMap-400px?fmt=png8&wid=250',
    'Iceberg & Indigo': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-IcebergIndigo-MiniMap-400px?fmt=png8&wid=250',
    'Moss & Sage': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-MossSage-MiniMap-400px?fmt=png8&wid=250',
    'Olive & Pine': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-OlivePine-MiniMap-400px?fmt=png8&wid=250',
    'Neutral': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-Neutral-MiniMap-400px?fmt=png8&wid=250',
    'Orange & Yellow': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-OrangeYellow-MiniMap-400px?fmt=png8&wid=250',
    'Peach & Saffron': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-PeachSaffron-MiniMap-400px?fmt=png8&wid=250',
    'Peacock & Sapphire': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-PeacockSapphire-MiniMap-400px?fmt=png8&wid=250',
    'Plum & Paprika': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-PlumPaprika-MiniMap-400px?fmt=png8&wid=250',
    'Sand & Bronze': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-SandBronze-MiniMap-400px?fmt=png8&wid=250',
    'Red & Pink': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-RedPink-MiniMap-400px?fmt=png8&wid=250',
    'Slate & Midnight': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-SlateMidnight-MiniMap-400px?fmt=png8&wid=250',
    'White': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-White-MiniMap-400px?fmt=png8&wid=250',
    'Wine & Coral': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-WineCoral-MiniMap-400px?fmt=png8&wid=250'
  }
}
