export default {
  hgsw: {
    grays: 'https://sherwin.scene7.com/is/image/sw/HGSW-Grays-MiniMap-400px?fmt=png8&wid=250',
    'clean-bright-1-3': 'https://sherwin.scene7.com/is/image/sw/HGSW-CleanBright-left-MiniMap-400px?fmt=png8&wid=250',
    'clean-bright-2-3': 'https://sherwin.scene7.com/is/image/sw/HGSW-CleanBright-middle-MiniMap-400px?fmt=png8&wid=250',
    'clean-bright-3-3': 'https://sherwin.scene7.com/is/image/sw/HGSW-CleanBright-right-MiniMap-400px?fmt=png8&wid=250',
    'muted-shaded-1-3': 'https://sherwin.scene7.com/is/image/sw/HGSW-MutedShaded-left-MiniMap-400px?fmt=png8&wid=250',
    'muted-shaded-2-3': 'https://sherwin.scene7.com/is/image/sw/HGSW-MutedShaded-middle-MiniMap-400px?fmt=png8&wid=250',
    'muted-shaded-3-3': 'https://sherwin.scene7.com/is/image/sw/HGSW-MutedShaded-right-MiniMap-400px?fmt=png8&wid=250',
    whites: 'https://sherwin.scene7.com/is/image/sw/HGSW-Whites-MiniMap-400px?fmt=png8&wid=250',
    neutrals: 'https://sherwin.scene7.com/is/image/sw/HGSW-Neutrals-MiniMap-400px?fmt=png8&wid=250'
  },
  valspar: {
    'bamboo-seagrass': 'https://sherwin.scene7.com/is/image/sw/Valspar-BambooSeagrass-MiniMap-400px?fmt=png8&wid=250',
    'chestnut-khaki': 'https://sherwin.scene7.com/is/image/sw/Valspar-ChestnutKhaki-MiniMap-400px?fmt=png8&wid=250',
    'blue-violet': 'https://sherwin.scene7.com/is/image/sw/Valspar-BlueViolet-MiniMap-400px?fmt=png8&wid=250',
    'fog-cocoa': 'https://sherwin.scene7.com/is/image/sw/Valspar-FogCocoa-MiniMap-400px?fmt=png8&wid=250',
    gray: 'https://sherwin.scene7.com/is/image/sw/Valspar-Gray-MiniMap-400px?fmt=png8&wid=250',
    'green-teal': 'https://sherwin.scene7.com/is/image/sw/Valspar-GreenTeal-MiniMap-400px?fmt=png8&wid=250',
    'iceberg-indigo': 'https://sherwin.scene7.com/is/image/sw/Valspar-IcebergIndigo-MiniMap-400px?fmt=png8&wid=250',
    'moss-sage': 'https://sherwin.scene7.com/is/image/sw/Valspar-MossSage-MiniMap-400px?fmt=png8&wid=250',
    'olive-pine': 'https://sherwin.scene7.com/is/image/sw/Valspar-OlivePine-MiniMap-400px?fmt=png8&wid=250',
    neutral: 'https://sherwin.scene7.com/is/image/sw/Valspar-Neutral-MiniMap-400px?fmt=png8&wid=250',
    'orange-yellow': 'https://sherwin.scene7.com/is/image/sw/Valspar-OrangeYellow-MiniMap-400px?fmt=png8&wid=250',
    'peach-saffron': 'https://sherwin.scene7.com/is/image/sw/Valspar-PeachSaffron-MiniMap-400px?fmt=png8&wid=250',
    'peacock-sapphire': 'https://sherwin.scene7.com/is/image/sw/Valspar-PeacockSapphire-MiniMap-400px?fmt=png8&wid=250',
    'plum-paprika': 'https://sherwin.scene7.com/is/image/sw/Valspar-PlumPaprika-MiniMap-400px?fmt=png8&wid=250',
    'sand-bronze': 'https://sherwin.scene7.com/is/image/sw/Valspar-SandBronze-MiniMap-400px?fmt=png8&wid=250',
    'red-pink': 'https://sherwin.scene7.com/is/image/sw/Valspar-RedPink-MiniMap-400px?fmt=png8&wid=250',
    'slate-midnight': 'https://sherwin.scene7.com/is/image/sw/Valspar-SlateMidnight-MiniMap-400px?fmt=png8&wid=250',
    white: 'https://sherwin.scene7.com/is/image/sw/Valspar-White-MiniMap-400px?fmt=png8&wid=250',
    'Wine-coral': 'https://sherwin.scene7.com/is/image/sw/Valspar-WineCoral-MiniMap-400px?fmt=png8&wid=250'
  },
  valsparLeftHand: {
    'bamboo-seagrass': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-BambooSeagrass-MiniMap-400px?fmt=png8&wid=250',
    'chestnut-khaki': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-ChestnutKhaki-MiniMap-400px?fmt=png8&wid=250',
    'blue-violet': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-BlueViolet-MiniMap-400px?fmt=png8&wid=250',
    'fog-cocoa': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-FogCocoa-MiniMap-400px?fmt=png8&wid=250',
    gray: 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-Gray-MiniMap-400px?fmt=png8&wid=250',
    'green-teal': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-GreenTeal-MiniMap-400px?fmt=png8&wid=250',
    'iceberg-indigo': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-IcebergIndigo-MiniMap-400px?fmt=png8&wid=250',
    'moss-sage': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-MossSage-MiniMap-400px?fmt=png8&wid=250',
    'olive-pine': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-OlivePine-MiniMap-400px?fmt=png8&wid=250',
    neutral: 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-Neutral-MiniMap-400px?fmt=png8&wid=250',
    'orange-yellow': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-OrangeYellow-MiniMap-400px?fmt=png8&wid=250',
    'peach-saffron': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-PeachSaffron-MiniMap-400px?fmt=png8&wid=250',
    'peacock-sapphire': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-PeacockSapphire-MiniMap-400px?fmt=png8&wid=250',
    'plum-paprika': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-PlumPaprika-MiniMap-400px?fmt=png8&wid=250',
    'sand-bronze': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-SandBronze-MiniMap-400px?fmt=png8&wid=250',
    'red-pink': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-RedPink-MiniMap-400px?fmt=png8&wid=250',
    'slate-midnight': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-SlateMidnight-MiniMap-400px?fmt=png8&wid=250',
    white: 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-White-MiniMap-400px?fmt=png8&wid=250',
    'wine-coral': 'https://sherwin.scene7.com/is/image/sw/Valspar-LeftHand-WineCoral-MiniMap-400px?fmt=png8&wid=250'
  }
}
