// flow-typed signature: 3605ae2cd4acd2e9d62c6e52453ddc30
// flow-typed version: <<STUB>>/@tensorflow-models/coco-ssd_v1.0.2/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tensorflow-models/coco-ssd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tensorflow-models/coco-ssd' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tensorflow-models/coco-ssd/dist/classes' {
  declare module.exports: any
}

declare module '@tensorflow-models/coco-ssd/dist/coco-ssd.esm' {
  declare module.exports: any
}

declare module '@tensorflow-models/coco-ssd/dist/coco-ssd' {
  declare module.exports: any
}

declare module '@tensorflow-models/coco-ssd/dist/coco-ssd.min' {
  declare module.exports: any
}

declare module '@tensorflow-models/coco-ssd/dist/index' {
  declare module.exports: any
}

declare module '@tensorflow-models/coco-ssd/dist/version' {
  declare module.exports: any
}

declare module '@tensorflow-models/coco-ssd/rollup.config' {
  declare module.exports: any
}

// Filename aliases
declare module '@tensorflow-models/coco-ssd/dist/classes.js' {
  declare module.exports: $Exports<'@tensorflow-models/coco-ssd/dist/classes'>
}
declare module '@tensorflow-models/coco-ssd/dist/coco-ssd.esm.js' {
  declare module.exports: $Exports<'@tensorflow-models/coco-ssd/dist/coco-ssd.esm'>
}
declare module '@tensorflow-models/coco-ssd/dist/coco-ssd.js' {
  declare module.exports: $Exports<'@tensorflow-models/coco-ssd/dist/coco-ssd'>
}
declare module '@tensorflow-models/coco-ssd/dist/coco-ssd.min.js' {
  declare module.exports: $Exports<'@tensorflow-models/coco-ssd/dist/coco-ssd.min'>
}
declare module '@tensorflow-models/coco-ssd/dist/index.js' {
  declare module.exports: $Exports<'@tensorflow-models/coco-ssd/dist/index'>
}
declare module '@tensorflow-models/coco-ssd/dist/version.js' {
  declare module.exports: $Exports<'@tensorflow-models/coco-ssd/dist/version'>
}
declare module '@tensorflow-models/coco-ssd/rollup.config.js' {
  declare module.exports: $Exports<'@tensorflow-models/coco-ssd/rollup.config'>
}
