// flow-typed signature: a9991a49360c4089c7563bee595a9320
// flow-typed version: <<STUB>>/@tensorflow-models/deeplab_v0.1.1/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tensorflow-models/deeplab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tensorflow-models/deeplab' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tensorflow-models/deeplab/dist/config' {
  declare module.exports: any;
}

declare module '@tensorflow-models/deeplab/dist/deeplab.esm' {
  declare module.exports: any;
}

declare module '@tensorflow-models/deeplab/dist/deeplab' {
  declare module.exports: any;
}

declare module '@tensorflow-models/deeplab/dist/deeplab.min' {
  declare module.exports: any;
}

declare module '@tensorflow-models/deeplab/dist' {
  declare module.exports: any;
}

declare module '@tensorflow-models/deeplab/dist/types' {
  declare module.exports: any;
}

declare module '@tensorflow-models/deeplab/dist/utils' {
  declare module.exports: any;
}

declare module '@tensorflow-models/deeplab/dist/version' {
  declare module.exports: any;
}

declare module '@tensorflow-models/deeplab/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tensorflow-models/deeplab/dist/config.js' {
  declare module.exports: $Exports<'@tensorflow-models/deeplab/dist/config'>;
}
declare module '@tensorflow-models/deeplab/dist/deeplab.esm.js' {
  declare module.exports: $Exports<'@tensorflow-models/deeplab/dist/deeplab.esm'>;
}
declare module '@tensorflow-models/deeplab/dist/deeplab.js' {
  declare module.exports: $Exports<'@tensorflow-models/deeplab/dist/deeplab'>;
}
declare module '@tensorflow-models/deeplab/dist/deeplab.min.js' {
  declare module.exports: $Exports<'@tensorflow-models/deeplab/dist/deeplab.min'>;
}
declare module '@tensorflow-models/deeplab/dist/index' {
  declare module.exports: $Exports<'@tensorflow-models/deeplab/dist'>;
}
declare module '@tensorflow-models/deeplab/dist/index.js' {
  declare module.exports: $Exports<'@tensorflow-models/deeplab/dist'>;
}
declare module '@tensorflow-models/deeplab/dist/types.js' {
  declare module.exports: $Exports<'@tensorflow-models/deeplab/dist/types'>;
}
declare module '@tensorflow-models/deeplab/dist/utils.js' {
  declare module.exports: $Exports<'@tensorflow-models/deeplab/dist/utils'>;
}
declare module '@tensorflow-models/deeplab/dist/version.js' {
  declare module.exports: $Exports<'@tensorflow-models/deeplab/dist/version'>;
}
declare module '@tensorflow-models/deeplab/rollup.config.js' {
  declare module.exports: $Exports<'@tensorflow-models/deeplab/rollup.config'>;
}
