// flow-typed signature: fb47387c6b48446f64fdf7981ce4da63
// flow-typed version: <<STUB>>/@types/react-dom_v18.0.5/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-dom' {
  declare module.exports: any
}
