// flow-typed signature: 58178077c135aac37d70cf3faa08a28e
// flow-typed version: <<STUB>>/@types/react_v18.0.14/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any
}
