// flow-typed signature: 41fcbd752adf464f6846885d538d1a70
// flow-typed version: <<STUB>>/@ctrl/tinycolor_v2.2.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ctrl/tinycolor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ctrl/tinycolor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ctrl/tinycolor/bundles/tinycolor.umd.min' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/conversion' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/css-color-names' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/es/conversion' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/es/css-color-names' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/es/format-input' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/es/from-ratio' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/es/index' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/es/interfaces' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/es/public_api' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/es/random' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/es/readability' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/es/to-ms-filter' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/es/umd_api' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/es/util' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/format-input' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/from-ratio' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/interfaces' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/public_api' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/random' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/readability' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/to-ms-filter' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/umd_api' {
  declare module.exports: any;
}

declare module '@ctrl/tinycolor/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ctrl/tinycolor/bundles/tinycolor.umd.min.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/bundles/tinycolor.umd.min'>;
}
declare module '@ctrl/tinycolor/conversion.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/conversion'>;
}
declare module '@ctrl/tinycolor/css-color-names.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/css-color-names'>;
}
declare module '@ctrl/tinycolor/es/conversion.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/es/conversion'>;
}
declare module '@ctrl/tinycolor/es/css-color-names.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/es/css-color-names'>;
}
declare module '@ctrl/tinycolor/es/format-input.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/es/format-input'>;
}
declare module '@ctrl/tinycolor/es/from-ratio.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/es/from-ratio'>;
}
declare module '@ctrl/tinycolor/es/index.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/es/index'>;
}
declare module '@ctrl/tinycolor/es/interfaces.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/es/interfaces'>;
}
declare module '@ctrl/tinycolor/es/public_api.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/es/public_api'>;
}
declare module '@ctrl/tinycolor/es/random.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/es/random'>;
}
declare module '@ctrl/tinycolor/es/readability.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/es/readability'>;
}
declare module '@ctrl/tinycolor/es/to-ms-filter.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/es/to-ms-filter'>;
}
declare module '@ctrl/tinycolor/es/umd_api.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/es/umd_api'>;
}
declare module '@ctrl/tinycolor/es/util.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/es/util'>;
}
declare module '@ctrl/tinycolor/format-input.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/format-input'>;
}
declare module '@ctrl/tinycolor/from-ratio.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/from-ratio'>;
}
declare module '@ctrl/tinycolor/index' {
  declare module.exports: $Exports<'@ctrl/tinycolor'>;
}
declare module '@ctrl/tinycolor/index.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor'>;
}
declare module '@ctrl/tinycolor/interfaces.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/interfaces'>;
}
declare module '@ctrl/tinycolor/public_api.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/public_api'>;
}
declare module '@ctrl/tinycolor/random.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/random'>;
}
declare module '@ctrl/tinycolor/readability.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/readability'>;
}
declare module '@ctrl/tinycolor/to-ms-filter.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/to-ms-filter'>;
}
declare module '@ctrl/tinycolor/umd_api.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/umd_api'>;
}
declare module '@ctrl/tinycolor/util.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/util'>;
}
