export const CLASS_NAMES = {
  BASE: 'color-swatch-inner',
  BASE_DYNAMIC: 'color-swatch-inner--dynamic',
  BASE_CLICKABLE: 'color-swatch-inner--clickable',
  BASE_FOCUS: 'color-swatch-inner--focus',
  BASE_ACTIVE: 'color-swatch-inner--active',
  BASE_BLOOM: 'color-swatch-inner--bloom',
  BASE_BLOOM_LVL_: 'color-swatch-inner--bloom-lvl-',
  BASE_COMPENSATE_X_: 'color-swatch-inner--compensate-x-',
  BASE_COMPENSATE_Y_: 'color-swatch-inner--compensate-y-',
  BASE_DARK: 'color-swatch-inner--dark-color',
  CONTENT: 'color-swatch-inner__content',
  CONTENT_NUMBER: 'color-swatch-inner__content__number',
  CONTENT_NAME: 'color-swatch-inner__content__name',
  SWATCH: 'color-wall-swatches__swatch',
  ENGAGE_LINK: 'color-swatch-inner__engage-link',
  CONTENT_CTA: 'color-swatch-inner__content__cta',
  CONTENT_CTA_L: 'color-swatch-inner__content__cta--l',
  CONTENT_CTA_R: 'color-swatch-inner__content__cta--r',
  CONTENT_CTA_FOCUS: 'color-swatch-inner__content__cta--focus'
}
