export const CLASS_NAMES = {
  BASE: 'color-swatch-inner',
  BASE_POS_T: 'color-swatch-inner--pos-t',
  BASE_POS_TL: 'color-swatch-inner--pos-tl',
  BASE_POS_TR: 'color-swatch-inner--pos-tr',
  BASE_POS_L: 'color-swatch-inner--pos-l',
  BASE_POS_R: 'color-swatch-inner--pos-r',
  BASE_POS_B: 'color-swatch-inner--pos-b',
  BASE_POS_BL: 'color-swatch-inner--pos-bl',
  BASE_POS_BR: 'color-swatch-inner--pos-br',
  BASE_DYNAMIC: 'color-swatch-inner--dynamic',
  BASE_CLICKABLE: 'color-swatch-inner--clickable',
  BASE_ACTIVE: 'color-swatch-inner--active',
  BASE_BLOOM: 'color-swatch-inner--bloom',
  BASE_BLOOM_CENTER: 'color-swatch-inner--bloom-center',
  BASE_BLOOM_LVL_: 'color-swatch-inner--bloom-lvl-',
  BASE_OFFSET_X_: 'color-swatch-inner--offset-x-',
  BASE_OFFSET_Y_: 'color-swatch-inner--offset-y-',
  BASE_COMPENSATE_X_: 'color-swatch-inner--compensate-x-',
  BASE_COMPENSATE_Y_: 'color-swatch-inner--compensate-y-',
  BASE_DARK: 'color-swatch-inner--dark-color',
  CONTENT: 'color-swatch-inner__content',
  CONTENT_NUMBER: 'color-swatch-inner__content__number',
  CONTENT_NAME: 'color-swatch-inner__content__name',
  CONTENT_ADD: 'color-swatch-inner__content__add',
  CONTENT_DETAILS: 'color-swatch-inner__content__details',
  SWATCH: 'color-wall-swatches__swatch'
}
