export const GLOBAL_MODAL_STYLE = {
  success: 'success',
  danger: 'danger',
  warning: 'warning',
  primary: 'primary',
  secondary: 'secondary'
}

export const HANDLE_NAVIGATION_INTENT_CONFIRM = 'HANDLE_NAVIGATION_INTENT_CONFIRM'
export const HANDLE_NAVIGATION_INTENT_CANCEL = 'HANDLE_NAVIGATION_INTENT_CANCEL'
export const HANDLE_DIRTY_NAVIGATION_INTENT_CONFIRM = 'HANDLE_DIRTY_NAVIGATION_INTENT_CONFRIM'
export const HANDLE_DIRTY_NAVIGATION_INTENT_CANCEL = 'HANDLE_DIRTY_NAVIGATION_INTENT_CANCEL'
export const HANDLE_SELECT_PALETTE_CONFIRM = 'HANDLE_SELECT_PALETTE_CONFIRM'
export const HANDLE_DELETE_MY_PREVIEW_CONFIRM = 'HANDLE_DELETE_MY_PREVIEW_CONFIRM'
export const HIDE_MODAL = 'HIDE_MODAL'
export const DANGER = 'DANGER'
export const PRIMARY = 'PRIMARY'
export const SAVED = 'Saved'
export const ACTION_SAVE = 'SAVE'

// @todo may be redundant with MODAL_TYPE_ENUM -RS
export const SAVE_OPTION = {
  SAVE_STOCK_SCENE: 'SAVE_STOCK_SCENE_FROM_MODAL',
  SAVE_PAINT_SCENE: 'SAVE_PAINT_SCENE_FROM_MODAL',
  SAVE_LIVE_PALETTE: 'SAVE_LIVE_PALETTE_FROM_MODAL',
  EMPTY_SCENE: 'EMPTY_SCENE',
  SAVE_FAST_MASK: 'SAVE_FAST_MASK'
}

export const MODAL_TYPE_ENUM = {
  MATCH_PHOTO: 'MATCH_PHOTO',
  STOCK_SCENE: 'STOCK_SCENE',
  PAINT_SCENE: 'PAINT_SCENE',
  LIVE_PALETTE: 'LIVE_PALETTE',
  EMPTY_SCENE: 'EMPTY_SCENE',
  FAST_MASK: 'FAST_MASK'
}
