// flow-typed signature: 30b512ca32798e79ed990d67eb4b2483
// flow-typed version: <<STUB>>/@ctrl/tinycolor_v2.6.0/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ctrl/tinycolor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ctrl/tinycolor' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ctrl/tinycolor/dist/bundles/tinycolor.umd.min' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/conversion' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/css-color-names' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/es/conversion' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/es/css-color-names' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/es/format-input' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/es/from-ratio' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/es' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/es/interfaces' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/es/public_api' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/es/random' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/es/readability' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/es/to-ms-filter' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/es/umd_api' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/es/util' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/format-input' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/from-ratio' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/interfaces' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/public_api' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/random' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/readability' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/to-ms-filter' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/umd_api' {
  declare module.exports: any
}

declare module '@ctrl/tinycolor/dist/util' {
  declare module.exports: any
}

// Filename aliases
declare module '@ctrl/tinycolor/dist/bundles/tinycolor.umd.min.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/bundles/tinycolor.umd.min'>
}
declare module '@ctrl/tinycolor/dist/conversion.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/conversion'>
}
declare module '@ctrl/tinycolor/dist/css-color-names.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/css-color-names'>
}
declare module '@ctrl/tinycolor/dist/es/conversion.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/es/conversion'>
}
declare module '@ctrl/tinycolor/dist/es/css-color-names.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/es/css-color-names'>
}
declare module '@ctrl/tinycolor/dist/es/format-input.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/es/format-input'>
}
declare module '@ctrl/tinycolor/dist/es/from-ratio.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/es/from-ratio'>
}
declare module '@ctrl/tinycolor/dist/es/index' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/es'>
}
declare module '@ctrl/tinycolor/dist/es/index.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/es'>
}
declare module '@ctrl/tinycolor/dist/es/interfaces.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/es/interfaces'>
}
declare module '@ctrl/tinycolor/dist/es/public_api.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/es/public_api'>
}
declare module '@ctrl/tinycolor/dist/es/random.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/es/random'>
}
declare module '@ctrl/tinycolor/dist/es/readability.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/es/readability'>
}
declare module '@ctrl/tinycolor/dist/es/to-ms-filter.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/es/to-ms-filter'>
}
declare module '@ctrl/tinycolor/dist/es/umd_api.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/es/umd_api'>
}
declare module '@ctrl/tinycolor/dist/es/util.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/es/util'>
}
declare module '@ctrl/tinycolor/dist/format-input.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/format-input'>
}
declare module '@ctrl/tinycolor/dist/from-ratio.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/from-ratio'>
}
declare module '@ctrl/tinycolor/dist/index' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist'>
}
declare module '@ctrl/tinycolor/dist/index.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist'>
}
declare module '@ctrl/tinycolor/dist/interfaces.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/interfaces'>
}
declare module '@ctrl/tinycolor/dist/public_api.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/public_api'>
}
declare module '@ctrl/tinycolor/dist/random.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/random'>
}
declare module '@ctrl/tinycolor/dist/readability.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/readability'>
}
declare module '@ctrl/tinycolor/dist/to-ms-filter.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/to-ms-filter'>
}
declare module '@ctrl/tinycolor/dist/umd_api.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/umd_api'>
}
declare module '@ctrl/tinycolor/dist/util.js' {
  declare module.exports: $Exports<'@ctrl/tinycolor/dist/util'>
}
