// flow-typed signature: 12115288627a96729c223dfd5d960e9e
// flow-typed version: <<STUB>>/@prism/toolkit_v3.3.0/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@prism/toolkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@prism/toolkit' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@prism/toolkit/__mocks__/heic2any' {
  declare module.exports: any
}

declare module '@prism/toolkit/babel-plugin-macros.config' {
  declare module.exports: any
}

declare module '@prism/toolkit/coverage/lcov-report/block-navigation' {
  declare module.exports: any
}

declare module '@prism/toolkit/coverage/lcov-report/prettify' {
  declare module.exports: any
}

declare module '@prism/toolkit/coverage/lcov-report/sorter' {
  declare module.exports: any
}

declare module '@prism/toolkit/cypress/plugins' {
  declare module.exports: any
}

declare module '@prism/toolkit/cypress/support/commands' {
  declare module.exports: any
}

declare module '@prism/toolkit/cypress/support' {
  declare module.exports: any
}

declare module '@prism/toolkit/dist/index.es' {
  declare module.exports: any
}

declare module '@prism/toolkit/dist' {
  declare module.exports: any
}

declare module '@prism/toolkit/lint-staged.config' {
  declare module.exports: any
}

declare module '@prism/toolkit/local_modules/postcss-root-bubbler' {
  declare module.exports: any
}

declare module '@prism/toolkit/local_modules/postcss-root-prefixer' {
  declare module.exports: any
}

declare module '@prism/toolkit/postcss.config' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/247.4c3216cab1479268739e.manager.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/247.a3b9dfc1.iframe.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/295.e8b9a6708014a7bfb2b7.manager.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/330.8047862b24a594b7e051.manager.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/331.757d9fed.iframe.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/331.77d79557b0a86a52c8d2.manager.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/423.bc94331f.iframe.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/423.d4adfdf8aac4f8cbad78.manager.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/446.ed185e0a.iframe.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/459.a9c203f2c764d94ab633.manager.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/459.ab5b0aa7.iframe.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/665.0c9b47e1c95724db34a4.manager.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/665.c22b3071.iframe.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/701.1281bc6d.iframe.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/869.1bc803b7.iframe.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/main.146e6952.iframe.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/main.9472e7a28ca90a940b02.manager.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/runtime~main.964f2a3f.iframe.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/public/runtime~main.ea739c62f28a2b5ff23d.manager.bundle' {
  declare module.exports: any
}

declare module '@prism/toolkit/rollup.config' {
  declare module.exports: any
}

declare module '@prism/toolkit/setupTests' {
  declare module.exports: any
}

declare module '@prism/toolkit/tailwind.config' {
  declare module.exports: any
}

// Filename aliases
declare module '@prism/toolkit/__mocks__/heic2any.js' {
  declare module.exports: $Exports<'@prism/toolkit/__mocks__/heic2any'>
}
declare module '@prism/toolkit/babel-plugin-macros.config.js' {
  declare module.exports: $Exports<'@prism/toolkit/babel-plugin-macros.config'>
}
declare module '@prism/toolkit/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'@prism/toolkit/coverage/lcov-report/block-navigation'>
}
declare module '@prism/toolkit/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'@prism/toolkit/coverage/lcov-report/prettify'>
}
declare module '@prism/toolkit/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'@prism/toolkit/coverage/lcov-report/sorter'>
}
declare module '@prism/toolkit/cypress/plugins/index' {
  declare module.exports: $Exports<'@prism/toolkit/cypress/plugins'>
}
declare module '@prism/toolkit/cypress/plugins/index.js' {
  declare module.exports: $Exports<'@prism/toolkit/cypress/plugins'>
}
declare module '@prism/toolkit/cypress/support/commands.js' {
  declare module.exports: $Exports<'@prism/toolkit/cypress/support/commands'>
}
declare module '@prism/toolkit/cypress/support/index' {
  declare module.exports: $Exports<'@prism/toolkit/cypress/support'>
}
declare module '@prism/toolkit/cypress/support/index.js' {
  declare module.exports: $Exports<'@prism/toolkit/cypress/support'>
}
declare module '@prism/toolkit/dist/index.es.js' {
  declare module.exports: $Exports<'@prism/toolkit/dist/index.es'>
}
declare module '@prism/toolkit/dist/index' {
  declare module.exports: $Exports<'@prism/toolkit/dist'>
}
declare module '@prism/toolkit/dist/index.js' {
  declare module.exports: $Exports<'@prism/toolkit/dist'>
}
declare module '@prism/toolkit/lint-staged.config.js' {
  declare module.exports: $Exports<'@prism/toolkit/lint-staged.config'>
}
declare module '@prism/toolkit/local_modules/postcss-root-bubbler.js' {
  declare module.exports: $Exports<'@prism/toolkit/local_modules/postcss-root-bubbler'>
}
declare module '@prism/toolkit/local_modules/postcss-root-prefixer.js' {
  declare module.exports: $Exports<'@prism/toolkit/local_modules/postcss-root-prefixer'>
}
declare module '@prism/toolkit/postcss.config.js' {
  declare module.exports: $Exports<'@prism/toolkit/postcss.config'>
}
declare module '@prism/toolkit/public/247.4c3216cab1479268739e.manager.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/247.4c3216cab1479268739e.manager.bundle'>
}
declare module '@prism/toolkit/public/247.a3b9dfc1.iframe.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/247.a3b9dfc1.iframe.bundle'>
}
declare module '@prism/toolkit/public/295.e8b9a6708014a7bfb2b7.manager.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/295.e8b9a6708014a7bfb2b7.manager.bundle'>
}
declare module '@prism/toolkit/public/330.8047862b24a594b7e051.manager.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/330.8047862b24a594b7e051.manager.bundle'>
}
declare module '@prism/toolkit/public/331.757d9fed.iframe.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/331.757d9fed.iframe.bundle'>
}
declare module '@prism/toolkit/public/331.77d79557b0a86a52c8d2.manager.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/331.77d79557b0a86a52c8d2.manager.bundle'>
}
declare module '@prism/toolkit/public/423.bc94331f.iframe.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/423.bc94331f.iframe.bundle'>
}
declare module '@prism/toolkit/public/423.d4adfdf8aac4f8cbad78.manager.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/423.d4adfdf8aac4f8cbad78.manager.bundle'>
}
declare module '@prism/toolkit/public/446.ed185e0a.iframe.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/446.ed185e0a.iframe.bundle'>
}
declare module '@prism/toolkit/public/459.a9c203f2c764d94ab633.manager.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/459.a9c203f2c764d94ab633.manager.bundle'>
}
declare module '@prism/toolkit/public/459.ab5b0aa7.iframe.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/459.ab5b0aa7.iframe.bundle'>
}
declare module '@prism/toolkit/public/665.0c9b47e1c95724db34a4.manager.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/665.0c9b47e1c95724db34a4.manager.bundle'>
}
declare module '@prism/toolkit/public/665.c22b3071.iframe.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/665.c22b3071.iframe.bundle'>
}
declare module '@prism/toolkit/public/701.1281bc6d.iframe.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/701.1281bc6d.iframe.bundle'>
}
declare module '@prism/toolkit/public/869.1bc803b7.iframe.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/869.1bc803b7.iframe.bundle'>
}
declare module '@prism/toolkit/public/main.146e6952.iframe.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/main.146e6952.iframe.bundle'>
}
declare module '@prism/toolkit/public/main.9472e7a28ca90a940b02.manager.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/main.9472e7a28ca90a940b02.manager.bundle'>
}
declare module '@prism/toolkit/public/runtime~main.964f2a3f.iframe.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/runtime~main.964f2a3f.iframe.bundle'>
}
declare module '@prism/toolkit/public/runtime~main.ea739c62f28a2b5ff23d.manager.bundle.js' {
  declare module.exports: $Exports<'@prism/toolkit/public/runtime~main.ea739c62f28a2b5ff23d.manager.bundle'>
}
declare module '@prism/toolkit/rollup.config.js' {
  declare module.exports: $Exports<'@prism/toolkit/rollup.config'>
}
declare module '@prism/toolkit/setupTests.js' {
  declare module.exports: $Exports<'@prism/toolkit/setupTests'>
}
declare module '@prism/toolkit/tailwind.config.js' {
  declare module.exports: $Exports<'@prism/toolkit/tailwind.config'>
}
