// flow-typed signature: d4bbe624e06f31ded3fc9bd3fd28ad1c
// flow-typed version: <<STUB>>/@babel/eslint-parser_v7.18.9/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any
}
