// flow-typed signature: d662c8c7cd603faae57c9b3a69e236da
// flow-typed version: <<STUB>>/@babel/plugin-transform-flow-strip-types_v7.18.9/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-flow-strip-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-flow-strip-types' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-flow-strip-types/lib' {
  declare module.exports: any
}

// Filename aliases
declare module '@babel/plugin-transform-flow-strip-types/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-flow-strip-types/lib'>
}
declare module '@babel/plugin-transform-flow-strip-types/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-flow-strip-types/lib'>
}
