// flow-typed signature: 113996fd6d5ef3d04f3c52503157a0cb
// flow-typed version: <<STUB>>/@babel/plugin-transform-template-literals_v7.18.9/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-template-literals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-template-literals' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-template-literals/lib' {
  declare module.exports: any
}

// Filename aliases
declare module '@babel/plugin-transform-template-literals/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-template-literals/lib'>
}
declare module '@babel/plugin-transform-template-literals/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-template-literals/lib'>
}
