// flow-typed signature: c17db8545ab400ed107f047bdf951bbd
// flow-typed version: <<STUB>>/@babel/plugin-transform-classes_v7.8.3/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-classes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-classes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-classes/lib' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-classes/lib/transformClass' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-classes/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-classes/lib'>;
}
declare module '@babel/plugin-transform-classes/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-classes/lib'>;
}
declare module '@babel/plugin-transform-classes/lib/transformClass.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-classes/lib/transformClass'>;
}
