// flow-typed signature: eec982ed00bb693a9bb4cc86d0dc2a7e
// flow-typed version: <<STUB>>/@babel/plugin-transform-object-assign_v7.18.6/flow_v0.183.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-object-assign'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-object-assign' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-object-assign/lib' {
  declare module.exports: any
}

// Filename aliases
declare module '@babel/plugin-transform-object-assign/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-object-assign/lib'>
}
declare module '@babel/plugin-transform-object-assign/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-object-assign/lib'>
}
