// flow-typed signature: 5c4bdf6faee0ed79ad4e9490c1f06237
// flow-typed version: <<STUB>>/@babel/plugin-syntax-export-default-from_v7.8.3/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-syntax-export-default-from'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-syntax-export-default-from' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-syntax-export-default-from/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-syntax-export-default-from/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-syntax-export-default-from/lib'>;
}
declare module '@babel/plugin-syntax-export-default-from/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-syntax-export-default-from/lib'>;
}
